/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2026_06_15.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2026_06_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * PayrollDigestResultsTotals
 * 
 * <p>Pay totals. `null` when the payroll has not been calculated, or when the calculation is stale (the
 * partner edited hours/earnings after the last calculation).
 */
public class PayrollDigestResultsTotals {
    /**
     * Total amount debited from the company bank account (string-formatted decimal).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("total_debit_amount")
    private Optional<String> totalDebitAmount;

    /**
     * Total net pay across all employees on this payroll (string-formatted decimal).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("net_pay")
    private Optional<String> netPay;

    /**
     * Total employer cost including taxes and benefits (string-formatted decimal).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("total_employer_cost")
    private Optional<String> totalEmployerCost;

    @JsonCreator
    public PayrollDigestResultsTotals(
            @JsonProperty("total_debit_amount") Optional<String> totalDebitAmount,
            @JsonProperty("net_pay") Optional<String> netPay,
            @JsonProperty("total_employer_cost") Optional<String> totalEmployerCost) {
        Utils.checkNotNull(totalDebitAmount, "totalDebitAmount");
        Utils.checkNotNull(netPay, "netPay");
        Utils.checkNotNull(totalEmployerCost, "totalEmployerCost");
        this.totalDebitAmount = totalDebitAmount;
        this.netPay = netPay;
        this.totalEmployerCost = totalEmployerCost;
    }
    
    public PayrollDigestResultsTotals() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Total amount debited from the company bank account (string-formatted decimal).
     */
    @JsonIgnore
    public Optional<String> totalDebitAmount() {
        return totalDebitAmount;
    }

    /**
     * Total net pay across all employees on this payroll (string-formatted decimal).
     */
    @JsonIgnore
    public Optional<String> netPay() {
        return netPay;
    }

    /**
     * Total employer cost including taxes and benefits (string-formatted decimal).
     */
    @JsonIgnore
    public Optional<String> totalEmployerCost() {
        return totalEmployerCost;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Total amount debited from the company bank account (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withTotalDebitAmount(String totalDebitAmount) {
        Utils.checkNotNull(totalDebitAmount, "totalDebitAmount");
        this.totalDebitAmount = Optional.ofNullable(totalDebitAmount);
        return this;
    }


    /**
     * Total amount debited from the company bank account (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withTotalDebitAmount(Optional<String> totalDebitAmount) {
        Utils.checkNotNull(totalDebitAmount, "totalDebitAmount");
        this.totalDebitAmount = totalDebitAmount;
        return this;
    }

    /**
     * Total net pay across all employees on this payroll (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withNetPay(String netPay) {
        Utils.checkNotNull(netPay, "netPay");
        this.netPay = Optional.ofNullable(netPay);
        return this;
    }


    /**
     * Total net pay across all employees on this payroll (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withNetPay(Optional<String> netPay) {
        Utils.checkNotNull(netPay, "netPay");
        this.netPay = netPay;
        return this;
    }

    /**
     * Total employer cost including taxes and benefits (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withTotalEmployerCost(String totalEmployerCost) {
        Utils.checkNotNull(totalEmployerCost, "totalEmployerCost");
        this.totalEmployerCost = Optional.ofNullable(totalEmployerCost);
        return this;
    }


    /**
     * Total employer cost including taxes and benefits (string-formatted decimal).
     */
    public PayrollDigestResultsTotals withTotalEmployerCost(Optional<String> totalEmployerCost) {
        Utils.checkNotNull(totalEmployerCost, "totalEmployerCost");
        this.totalEmployerCost = totalEmployerCost;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayrollDigestResultsTotals other = (PayrollDigestResultsTotals) o;
        return 
            Utils.enhancedDeepEquals(this.totalDebitAmount, other.totalDebitAmount) &&
            Utils.enhancedDeepEquals(this.netPay, other.netPay) &&
            Utils.enhancedDeepEquals(this.totalEmployerCost, other.totalEmployerCost);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            totalDebitAmount, netPay, totalEmployerCost);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PayrollDigestResultsTotals.class,
                "totalDebitAmount", totalDebitAmount,
                "netPay", netPay,
                "totalEmployerCost", totalEmployerCost);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> totalDebitAmount = Optional.empty();

        private Optional<String> netPay = Optional.empty();

        private Optional<String> totalEmployerCost = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Total amount debited from the company bank account (string-formatted decimal).
         */
        public Builder totalDebitAmount(String totalDebitAmount) {
            Utils.checkNotNull(totalDebitAmount, "totalDebitAmount");
            this.totalDebitAmount = Optional.ofNullable(totalDebitAmount);
            return this;
        }

        /**
         * Total amount debited from the company bank account (string-formatted decimal).
         */
        public Builder totalDebitAmount(Optional<String> totalDebitAmount) {
            Utils.checkNotNull(totalDebitAmount, "totalDebitAmount");
            this.totalDebitAmount = totalDebitAmount;
            return this;
        }


        /**
         * Total net pay across all employees on this payroll (string-formatted decimal).
         */
        public Builder netPay(String netPay) {
            Utils.checkNotNull(netPay, "netPay");
            this.netPay = Optional.ofNullable(netPay);
            return this;
        }

        /**
         * Total net pay across all employees on this payroll (string-formatted decimal).
         */
        public Builder netPay(Optional<String> netPay) {
            Utils.checkNotNull(netPay, "netPay");
            this.netPay = netPay;
            return this;
        }


        /**
         * Total employer cost including taxes and benefits (string-formatted decimal).
         */
        public Builder totalEmployerCost(String totalEmployerCost) {
            Utils.checkNotNull(totalEmployerCost, "totalEmployerCost");
            this.totalEmployerCost = Optional.ofNullable(totalEmployerCost);
            return this;
        }

        /**
         * Total employer cost including taxes and benefits (string-formatted decimal).
         */
        public Builder totalEmployerCost(Optional<String> totalEmployerCost) {
            Utils.checkNotNull(totalEmployerCost, "totalEmployerCost");
            this.totalEmployerCost = totalEmployerCost;
            return this;
        }

        public PayrollDigestResultsTotals build() {

            return new PayrollDigestResultsTotals(
                totalDebitAmount, netPay, totalEmployerCost);
        }

    }
}
