/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations.async;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.models.operations.DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion;
import com.gusto.embedded_api_v_2025_11_15.models.operations.DeleteV1TimeOffRequestsTimeOffRequestUuidRequest;
import com.gusto.embedded_api_v_2025_11_15.operations.DeleteV1TimeOffRequestsTimeOffRequestUuid;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class DeleteV1TimeOffRequestsTimeOffRequestUuidRequestBuilder {

    private Optional<? extends DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion>>() {});
    private String timeOffRequestUuid;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteV1TimeOffRequestsTimeOffRequestUuidRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public DeleteV1TimeOffRequestsTimeOffRequestUuidRequestBuilder xGustoAPIVersion(DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public DeleteV1TimeOffRequestsTimeOffRequestUuidRequestBuilder xGustoAPIVersion(Optional<? extends DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public DeleteV1TimeOffRequestsTimeOffRequestUuidRequestBuilder timeOffRequestUuid(String timeOffRequestUuid) {
        Utils.checkNotNull(timeOffRequestUuid, "timeOffRequestUuid");
        this.timeOffRequestUuid = timeOffRequestUuid;
        return this;
    }


    private DeleteV1TimeOffRequestsTimeOffRequestUuidRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        DeleteV1TimeOffRequestsTimeOffRequestUuidRequest request = new DeleteV1TimeOffRequestsTimeOffRequestUuidRequest(xGustoAPIVersion,
            timeOffRequestUuid);

        return request;
    }

    public CompletableFuture<DeleteV1TimeOffRequestsTimeOffRequestUuidResponse> call() {
        
        AsyncRequestOperation<DeleteV1TimeOffRequestsTimeOffRequestUuidRequest, DeleteV1TimeOffRequestsTimeOffRequestUuidResponse> operation
              = new DeleteV1TimeOffRequestsTimeOffRequestUuid.Async(sdkConfiguration, _headers);
        DeleteV1TimeOffRequestsTimeOffRequestUuidRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends DeleteV1TimeOffRequestsTimeOffRequestUuidHeaderXGustoAPIVersion>>() {});
}
