/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations.async;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.models.components.EmployeeSection603HighEarnerStatusCreateRequest;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest;
import com.gusto.embedded_api_v_2025_11_15.operations.PostV1EmployeesEmployeeUuidSection603HighEarnerStatuses;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder {

    private String employeeUuid;
    private Optional<? extends PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion>>() {});
    private EmployeeSection603HighEarnerStatusCreateRequest employeeSection603HighEarnerStatusCreateRequest;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder employeeUuid(String employeeUuid) {
        Utils.checkNotNull(employeeUuid, "employeeUuid");
        this.employeeUuid = employeeUuid;
        return this;
    }
                
    public PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder xGustoAPIVersion(PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder xGustoAPIVersion(Optional<? extends PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequestBuilder employeeSection603HighEarnerStatusCreateRequest(EmployeeSection603HighEarnerStatusCreateRequest employeeSection603HighEarnerStatusCreateRequest) {
        Utils.checkNotNull(employeeSection603HighEarnerStatusCreateRequest, "employeeSection603HighEarnerStatusCreateRequest");
        this.employeeSection603HighEarnerStatusCreateRequest = employeeSection603HighEarnerStatusCreateRequest;
        return this;
    }


    private PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest request = new PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest(employeeUuid,
            xGustoAPIVersion,
            employeeSection603HighEarnerStatusCreateRequest);

        return request;
    }

    public CompletableFuture<PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesResponse> call() {
        
        AsyncRequestOperation<PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest, PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesResponse> operation
              = new PostV1EmployeesEmployeeUuidSection603HighEarnerStatuses.Async(sdkConfiguration, _headers);
        PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PostV1EmployeesEmployeeUuidSection603HighEarnerStatusesHeaderXGustoAPIVersion>>() {});
}
