/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gusto.embedded_api_v_2025_11_15.models.components.WebhookSubscription;
import com.gusto.embedded_api_v_2025_11_15.utils.AsyncResponse;
import com.gusto.embedded_api_v_2025_11_15.utils.Blob;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class PutV1VerifyWebhookSubscriptionUuidResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * successful
     */
    private Optional<? extends WebhookSubscription> webhookSubscription;

    @JsonCreator
    public PutV1VerifyWebhookSubscriptionUuidResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends WebhookSubscription> webhookSubscription) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(webhookSubscription, "webhookSubscription");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.webhookSubscription = webhookSubscription;
    }
    
    public PutV1VerifyWebhookSubscriptionUuidResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * successful
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<WebhookSubscription> webhookSubscription() {
        return (Optional<WebhookSubscription>) webhookSubscription;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public PutV1VerifyWebhookSubscriptionUuidResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public PutV1VerifyWebhookSubscriptionUuidResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public PutV1VerifyWebhookSubscriptionUuidResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * successful
     */
    public PutV1VerifyWebhookSubscriptionUuidResponse withWebhookSubscription(WebhookSubscription webhookSubscription) {
        Utils.checkNotNull(webhookSubscription, "webhookSubscription");
        this.webhookSubscription = Optional.ofNullable(webhookSubscription);
        return this;
    }


    /**
     * successful
     */
    public PutV1VerifyWebhookSubscriptionUuidResponse withWebhookSubscription(Optional<? extends WebhookSubscription> webhookSubscription) {
        Utils.checkNotNull(webhookSubscription, "webhookSubscription");
        this.webhookSubscription = webhookSubscription;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutV1VerifyWebhookSubscriptionUuidResponse other = (PutV1VerifyWebhookSubscriptionUuidResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.webhookSubscription, other.webhookSubscription);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            webhookSubscription);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutV1VerifyWebhookSubscriptionUuidResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "webhookSubscription", webhookSubscription);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends WebhookSubscription> webhookSubscription = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * successful
         */
        public Builder webhookSubscription(WebhookSubscription webhookSubscription) {
            Utils.checkNotNull(webhookSubscription, "webhookSubscription");
            this.webhookSubscription = Optional.ofNullable(webhookSubscription);
            return this;
        }

        /**
         * successful
         */
        public Builder webhookSubscription(Optional<? extends WebhookSubscription> webhookSubscription) {
            Utils.checkNotNull(webhookSubscription, "webhookSubscription");
            this.webhookSubscription = webhookSubscription;
            return this;
        }

        public PutV1VerifyWebhookSubscriptionUuidResponse build() {

            return new PutV1VerifyWebhookSubscriptionUuidResponse(
                contentType, statusCode, rawResponse,
                webhookSubscription);
        }

    }
}
