/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations.async;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1WorkAddressesWorkAddressUuidRequest;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1WorkAddressesWorkAddressUuidRequestBody;
import com.gusto.embedded_api_v_2025_11_15.operations.PutV1WorkAddressesWorkAddressUuid;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class PutV1WorkAddressesWorkAddressUuidRequestBuilder {

    private String workAddressUuid;
    private Optional<? extends PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion>>() {});
    private PutV1WorkAddressesWorkAddressUuidRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PutV1WorkAddressesWorkAddressUuidRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public PutV1WorkAddressesWorkAddressUuidRequestBuilder workAddressUuid(String workAddressUuid) {
        Utils.checkNotNull(workAddressUuid, "workAddressUuid");
        this.workAddressUuid = workAddressUuid;
        return this;
    }
                
    public PutV1WorkAddressesWorkAddressUuidRequestBuilder xGustoAPIVersion(PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PutV1WorkAddressesWorkAddressUuidRequestBuilder xGustoAPIVersion(Optional<? extends PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PutV1WorkAddressesWorkAddressUuidRequestBuilder requestBody(PutV1WorkAddressesWorkAddressUuidRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private PutV1WorkAddressesWorkAddressUuidRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PutV1WorkAddressesWorkAddressUuidRequest request = new PutV1WorkAddressesWorkAddressUuidRequest(workAddressUuid,
            xGustoAPIVersion,
            requestBody);

        return request;
    }

    public CompletableFuture<PutV1WorkAddressesWorkAddressUuidResponse> call() {
        
        AsyncRequestOperation<PutV1WorkAddressesWorkAddressUuidRequest, PutV1WorkAddressesWorkAddressUuidResponse> operation
              = new PutV1WorkAddressesWorkAddressUuid.Async(sdkConfiguration, _headers);
        PutV1WorkAddressesWorkAddressUuidRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PutV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion>>() {});
}
