/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.SpeakeasyMetadata;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class GetV1PayrollDigestsPayrollDigestUuidRequest {
    /**
     * The UUID of the payroll digest batch returned by `POST /v1/payroll_digests`.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=payroll_digest_uuid")
    private String payrollDigestUuid;

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion;

    @JsonCreator
    public GetV1PayrollDigestsPayrollDigestUuidRequest(
            String payrollDigestUuid,
            Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(payrollDigestUuid, "payrollDigestUuid");
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.payrollDigestUuid = payrollDigestUuid;
        this.xGustoAPIVersion = xGustoAPIVersion;
    }
    
    public GetV1PayrollDigestsPayrollDigestUuidRequest(
            String payrollDigestUuid) {
        this(payrollDigestUuid, Optional.empty());
    }

    /**
     * The UUID of the payroll digest batch returned by `POST /v1/payroll_digests`.
     */
    @JsonIgnore
    public String payrollDigestUuid() {
        return payrollDigestUuid;
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The UUID of the payroll digest batch returned by `POST /v1/payroll_digests`.
     */
    public GetV1PayrollDigestsPayrollDigestUuidRequest withPayrollDigestUuid(String payrollDigestUuid) {
        Utils.checkNotNull(payrollDigestUuid, "payrollDigestUuid");
        this.payrollDigestUuid = payrollDigestUuid;
        return this;
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetV1PayrollDigestsPayrollDigestUuidRequest withXGustoAPIVersion(GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public GetV1PayrollDigestsPayrollDigestUuidRequest withXGustoAPIVersion(Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetV1PayrollDigestsPayrollDigestUuidRequest other = (GetV1PayrollDigestsPayrollDigestUuidRequest) o;
        return 
            Utils.enhancedDeepEquals(this.payrollDigestUuid, other.payrollDigestUuid) &&
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            payrollDigestUuid, xGustoAPIVersion);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetV1PayrollDigestsPayrollDigestUuidRequest.class,
                "payrollDigestUuid", payrollDigestUuid,
                "xGustoAPIVersion", xGustoAPIVersion);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String payrollDigestUuid;

        private Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The UUID of the payroll digest batch returned by `POST /v1/payroll_digests`.
         */
        public Builder payrollDigestUuid(String payrollDigestUuid) {
            Utils.checkNotNull(payrollDigestUuid, "payrollDigestUuid");
            this.payrollDigestUuid = payrollDigestUuid;
            return this;
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }

        public GetV1PayrollDigestsPayrollDigestUuidRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new GetV1PayrollDigestsPayrollDigestUuidRequest(
                payrollDigestUuid, xGustoAPIVersion);
        }


        private static final LazySingletonValue<Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2025-06-15\"",
                        new TypeReference<Optional<? extends GetV1PayrollDigestsPayrollDigestUuidHeaderXGustoAPIVersion>>() {});
    }
}
