/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion
 * 
 * <p>Determines the date-based API version associated with your API call. If none is provided, your
 * application's [minimum API
 * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
public enum PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion {
    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS06_MINUS15("2025-06-15");

    @JsonValue
    private final String value;

    PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion> fromValue(String value) {
        for (PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion o: PutV1ContractorsContractorUuidAddressHeaderXGustoAPIVersion.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

