/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.operations.async;

import static com.gusto.embedded_api.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api.SDKConfiguration;
import com.gusto.embedded_api.models.operations.GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion;
import com.gusto.embedded_api.models.operations.GetV1ExternalPayrollCalculateTaxesRequest;
import com.gusto.embedded_api.operations.GetV1ExternalPayrollCalculateTaxes;
import com.gusto.embedded_api.utils.Headers;
import com.gusto.embedded_api.utils.LazySingletonValue;
import com.gusto.embedded_api.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class GetV1ExternalPayrollCalculateTaxesRequestBuilder {

    private Optional<? extends GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-06-15\"",
                            new TypeReference<Optional<? extends GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion>>() {});
    private String companyUuid;
    private String externalPayrollId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetV1ExternalPayrollCalculateTaxesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetV1ExternalPayrollCalculateTaxesRequestBuilder xGustoAPIVersion(GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public GetV1ExternalPayrollCalculateTaxesRequestBuilder xGustoAPIVersion(Optional<? extends GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public GetV1ExternalPayrollCalculateTaxesRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }

    public GetV1ExternalPayrollCalculateTaxesRequestBuilder externalPayrollId(String externalPayrollId) {
        Utils.checkNotNull(externalPayrollId, "externalPayrollId");
        this.externalPayrollId = externalPayrollId;
        return this;
    }


    private GetV1ExternalPayrollCalculateTaxesRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        GetV1ExternalPayrollCalculateTaxesRequest request = new GetV1ExternalPayrollCalculateTaxesRequest(xGustoAPIVersion,
            companyUuid,
            externalPayrollId);

        return request;
    }

    public CompletableFuture<GetV1ExternalPayrollCalculateTaxesResponse> call() {
        
        AsyncRequestOperation<GetV1ExternalPayrollCalculateTaxesRequest, GetV1ExternalPayrollCalculateTaxesResponse> operation
              = new GetV1ExternalPayrollCalculateTaxes.Async(sdkConfiguration, _headers);
        GetV1ExternalPayrollCalculateTaxesRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<? extends GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-06-15\"",
                    new TypeReference<Optional<? extends GetV1ExternalPayrollCalculateTaxesHeaderXGustoAPIVersion>>() {});
}
