/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.operations.GetV1ContractorsContractorUuidBankAccounts;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetV1ContractorsContractorUuidBankAccountsRequestBuilder {

    private Optional<? extends GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion>>() {});
    private String contractorUuid;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetV1ContractorsContractorUuidBankAccountsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetV1ContractorsContractorUuidBankAccountsRequestBuilder xGustoAPIVersion(GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public GetV1ContractorsContractorUuidBankAccountsRequestBuilder xGustoAPIVersion(Optional<? extends GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public GetV1ContractorsContractorUuidBankAccountsRequestBuilder contractorUuid(String contractorUuid) {
        Utils.checkNotNull(contractorUuid, "contractorUuid");
        this.contractorUuid = contractorUuid;
        return this;
    }


    private GetV1ContractorsContractorUuidBankAccountsRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        GetV1ContractorsContractorUuidBankAccountsRequest request = new GetV1ContractorsContractorUuidBankAccountsRequest(xGustoAPIVersion,
            contractorUuid);

        return request;
    }

    public GetV1ContractorsContractorUuidBankAccountsResponse call() {
        
        RequestOperation<GetV1ContractorsContractorUuidBankAccountsRequest, GetV1ContractorsContractorUuidBankAccountsResponse> operation
              = new GetV1ContractorsContractorUuidBankAccounts.Sync(sdkConfiguration, _headers);
        GetV1ContractorsContractorUuidBankAccountsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends GetV1ContractorsContractorUuidBankAccountsHeaderXGustoAPIVersion>>() {});
}
