/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gusto.embedded_api_v_2025_11_15.models.components.CompanyBenefit;
import com.gusto.embedded_api_v_2025_11_15.utils.Response;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;


public class GetV1CompaniesCompanyIdCompanyBenefitsResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Example response
     */
    private Optional<? extends List<CompanyBenefit>> companyBenefits;

    @JsonCreator
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends List<CompanyBenefit>> companyBenefits) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(companyBenefits, "companyBenefits");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.companyBenefits = companyBenefits;
    }
    
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Example response
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<CompanyBenefit>> companyBenefits() {
        return (Optional<List<CompanyBenefit>>) companyBenefits;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Example response
     */
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse withCompanyBenefits(List<CompanyBenefit> companyBenefits) {
        Utils.checkNotNull(companyBenefits, "companyBenefits");
        this.companyBenefits = Optional.ofNullable(companyBenefits);
        return this;
    }


    /**
     * Example response
     */
    public GetV1CompaniesCompanyIdCompanyBenefitsResponse withCompanyBenefits(Optional<? extends List<CompanyBenefit>> companyBenefits) {
        Utils.checkNotNull(companyBenefits, "companyBenefits");
        this.companyBenefits = companyBenefits;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetV1CompaniesCompanyIdCompanyBenefitsResponse other = (GetV1CompaniesCompanyIdCompanyBenefitsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.companyBenefits, other.companyBenefits);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            companyBenefits);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetV1CompaniesCompanyIdCompanyBenefitsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "companyBenefits", companyBenefits);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends List<CompanyBenefit>> companyBenefits = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Example response
         */
        public Builder companyBenefits(List<CompanyBenefit> companyBenefits) {
            Utils.checkNotNull(companyBenefits, "companyBenefits");
            this.companyBenefits = Optional.ofNullable(companyBenefits);
            return this;
        }

        /**
         * Example response
         */
        public Builder companyBenefits(Optional<? extends List<CompanyBenefit>> companyBenefits) {
            Utils.checkNotNull(companyBenefits, "companyBenefits");
            this.companyBenefits = companyBenefits;
            return this;
        }

        public GetV1CompaniesCompanyIdCompanyBenefitsResponse build() {

            return new GetV1CompaniesCompanyIdCompanyBenefitsResponse(
                contentType, statusCode, rawResponse,
                companyBenefits);
        }

    }
}
