/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod
 * 
 * <p>Payment method for the contractor
 */
public enum PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod {
    DIRECT_DEPOSIT("Direct Deposit"),
    CHECK("Check");

    @JsonValue
    private final String value;

    PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod> fromValue(String value) {
        for (PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod o: PatchV1ContractorPaymentGroupsIdPartnerDisbursementsPaymentMethod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

