/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.models.components.AdminCreateRequest;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.SpeakeasyMetadata;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class PostV1CompaniesCompanyIdAdminsRequest {
    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion;

    /**
     * The UUID of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company_id")
    private String companyId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private AdminCreateRequest adminCreateRequest;

    @JsonCreator
    public PostV1CompaniesCompanyIdAdminsRequest(
            Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion,
            String companyId,
            AdminCreateRequest adminCreateRequest) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(companyId, "companyId");
        Utils.checkNotNull(adminCreateRequest, "adminCreateRequest");
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.companyId = companyId;
        this.adminCreateRequest = adminCreateRequest;
    }
    
    public PostV1CompaniesCompanyIdAdminsRequest(
            String companyId,
            AdminCreateRequest adminCreateRequest) {
        this(Optional.empty(), companyId, adminCreateRequest);
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    /**
     * The UUID of the company
     */
    @JsonIgnore
    public String companyId() {
        return companyId;
    }

    @JsonIgnore
    public AdminCreateRequest adminCreateRequest() {
        return adminCreateRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PostV1CompaniesCompanyIdAdminsRequest withXGustoAPIVersion(PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PostV1CompaniesCompanyIdAdminsRequest withXGustoAPIVersion(Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    /**
     * The UUID of the company
     */
    public PostV1CompaniesCompanyIdAdminsRequest withCompanyId(String companyId) {
        Utils.checkNotNull(companyId, "companyId");
        this.companyId = companyId;
        return this;
    }

    public PostV1CompaniesCompanyIdAdminsRequest withAdminCreateRequest(AdminCreateRequest adminCreateRequest) {
        Utils.checkNotNull(adminCreateRequest, "adminCreateRequest");
        this.adminCreateRequest = adminCreateRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostV1CompaniesCompanyIdAdminsRequest other = (PostV1CompaniesCompanyIdAdminsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Utils.enhancedDeepEquals(this.companyId, other.companyId) &&
            Utils.enhancedDeepEquals(this.adminCreateRequest, other.adminCreateRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xGustoAPIVersion, companyId, adminCreateRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostV1CompaniesCompanyIdAdminsRequest.class,
                "xGustoAPIVersion", xGustoAPIVersion,
                "companyId", companyId,
                "adminCreateRequest", adminCreateRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion;

        private String companyId;

        private AdminCreateRequest adminCreateRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }


        /**
         * The UUID of the company
         */
        public Builder companyId(String companyId) {
            Utils.checkNotNull(companyId, "companyId");
            this.companyId = companyId;
            return this;
        }


        public Builder adminCreateRequest(AdminCreateRequest adminCreateRequest) {
            Utils.checkNotNull(adminCreateRequest, "adminCreateRequest");
            this.adminCreateRequest = adminCreateRequest;
            return this;
        }

        public PostV1CompaniesCompanyIdAdminsRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new PostV1CompaniesCompanyIdAdminsRequest(
                xGustoAPIVersion, companyId, adminCreateRequest);
        }


        private static final LazySingletonValue<Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2025-11-15\"",
                        new TypeReference<Optional<? extends PostV1CompaniesCompanyIdAdminsHeaderXGustoAPIVersion>>() {});
    }
}
