/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;


public class PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody {
    /**
     * The UUID of the employee
     */
    @JsonProperty("employee_uuid")
    private String employeeUuid;

    /**
     * The UUID of the time off policy
     */
    @JsonProperty("policy_uuid")
    private String policyUuid;

    /**
     * A note from the employee about the request
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("employee_note")
    private Optional<String> employeeNote;

    /**
     * The start date of the time off request (YYYY-MM-DD)
     */
    @JsonProperty("start_date")
    private String startDate;

    /**
     * The end date of the time off request (YYYY-MM-DD)
     */
    @JsonProperty("end_date")
    private String endDate;

    /**
     * An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g.
     * {"2025-01-20": "8.000"})
     */
    @JsonProperty("days")
    private Map<String, String> days;

    @JsonCreator
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody(
            @JsonProperty("employee_uuid") String employeeUuid,
            @JsonProperty("policy_uuid") String policyUuid,
            @JsonProperty("employee_note") Optional<String> employeeNote,
            @JsonProperty("start_date") String startDate,
            @JsonProperty("end_date") String endDate,
            @JsonProperty("days") Map<String, String> days) {
        Utils.checkNotNull(employeeUuid, "employeeUuid");
        Utils.checkNotNull(policyUuid, "policyUuid");
        Utils.checkNotNull(employeeNote, "employeeNote");
        Utils.checkNotNull(startDate, "startDate");
        Utils.checkNotNull(endDate, "endDate");
        days = Utils.emptyMapIfNull(days);
        Utils.checkNotNull(days, "days");
        this.employeeUuid = employeeUuid;
        this.policyUuid = policyUuid;
        this.employeeNote = employeeNote;
        this.startDate = startDate;
        this.endDate = endDate;
        this.days = days;
    }
    
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody(
            String employeeUuid,
            String policyUuid,
            String startDate,
            String endDate,
            Map<String, String> days) {
        this(employeeUuid, policyUuid, Optional.empty(),
            startDate, endDate, days);
    }

    /**
     * The UUID of the employee
     */
    @JsonIgnore
    public String employeeUuid() {
        return employeeUuid;
    }

    /**
     * The UUID of the time off policy
     */
    @JsonIgnore
    public String policyUuid() {
        return policyUuid;
    }

    /**
     * A note from the employee about the request
     */
    @JsonIgnore
    public Optional<String> employeeNote() {
        return employeeNote;
    }

    /**
     * The start date of the time off request (YYYY-MM-DD)
     */
    @JsonIgnore
    public String startDate() {
        return startDate;
    }

    /**
     * The end date of the time off request (YYYY-MM-DD)
     */
    @JsonIgnore
    public String endDate() {
        return endDate;
    }

    /**
     * An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g.
     * {"2025-01-20": "8.000"})
     */
    @JsonIgnore
    public Map<String, String> days() {
        return days;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The UUID of the employee
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withEmployeeUuid(String employeeUuid) {
        Utils.checkNotNull(employeeUuid, "employeeUuid");
        this.employeeUuid = employeeUuid;
        return this;
    }

    /**
     * The UUID of the time off policy
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withPolicyUuid(String policyUuid) {
        Utils.checkNotNull(policyUuid, "policyUuid");
        this.policyUuid = policyUuid;
        return this;
    }

    /**
     * A note from the employee about the request
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withEmployeeNote(String employeeNote) {
        Utils.checkNotNull(employeeNote, "employeeNote");
        this.employeeNote = Optional.ofNullable(employeeNote);
        return this;
    }


    /**
     * A note from the employee about the request
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withEmployeeNote(Optional<String> employeeNote) {
        Utils.checkNotNull(employeeNote, "employeeNote");
        this.employeeNote = employeeNote;
        return this;
    }

    /**
     * The start date of the time off request (YYYY-MM-DD)
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withStartDate(String startDate) {
        Utils.checkNotNull(startDate, "startDate");
        this.startDate = startDate;
        return this;
    }

    /**
     * The end date of the time off request (YYYY-MM-DD)
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withEndDate(String endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = endDate;
        return this;
    }

    /**
     * An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g.
     * {"2025-01-20": "8.000"})
     */
    public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody withDays(Map<String, String> days) {
        Utils.checkNotNull(days, "days");
        this.days = days;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody other = (PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.employeeUuid, other.employeeUuid) &&
            Utils.enhancedDeepEquals(this.policyUuid, other.policyUuid) &&
            Utils.enhancedDeepEquals(this.employeeNote, other.employeeNote) &&
            Utils.enhancedDeepEquals(this.startDate, other.startDate) &&
            Utils.enhancedDeepEquals(this.endDate, other.endDate) &&
            Utils.enhancedDeepEquals(this.days, other.days);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            employeeUuid, policyUuid, employeeNote,
            startDate, endDate, days);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody.class,
                "employeeUuid", employeeUuid,
                "policyUuid", policyUuid,
                "employeeNote", employeeNote,
                "startDate", startDate,
                "endDate", endDate,
                "days", days);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String employeeUuid;

        private String policyUuid;

        private Optional<String> employeeNote = Optional.empty();

        private String startDate;

        private String endDate;

        private Map<String, String> days;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The UUID of the employee
         */
        public Builder employeeUuid(String employeeUuid) {
            Utils.checkNotNull(employeeUuid, "employeeUuid");
            this.employeeUuid = employeeUuid;
            return this;
        }


        /**
         * The UUID of the time off policy
         */
        public Builder policyUuid(String policyUuid) {
            Utils.checkNotNull(policyUuid, "policyUuid");
            this.policyUuid = policyUuid;
            return this;
        }


        /**
         * A note from the employee about the request
         */
        public Builder employeeNote(String employeeNote) {
            Utils.checkNotNull(employeeNote, "employeeNote");
            this.employeeNote = Optional.ofNullable(employeeNote);
            return this;
        }

        /**
         * A note from the employee about the request
         */
        public Builder employeeNote(Optional<String> employeeNote) {
            Utils.checkNotNull(employeeNote, "employeeNote");
            this.employeeNote = employeeNote;
            return this;
        }


        /**
         * The start date of the time off request (YYYY-MM-DD)
         */
        public Builder startDate(String startDate) {
            Utils.checkNotNull(startDate, "startDate");
            this.startDate = startDate;
            return this;
        }


        /**
         * The end date of the time off request (YYYY-MM-DD)
         */
        public Builder endDate(String endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = endDate;
            return this;
        }


        /**
         * An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g.
         * {"2025-01-20": "8.000"})
         */
        public Builder days(Map<String, String> days) {
            Utils.checkNotNull(days, "days");
            this.days = days;
            return this;
        }

        public PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody build() {

            return new PostV1CompaniesCompanyUuidTimeOffRequestsRequestBody(
                employeeUuid, policyUuid, employeeNote,
                startDate, endDate, days);
        }

    }
}
