/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.RequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.operations.PostCompaniesCompanyUuidSuspensions;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class PostCompaniesCompanyUuidSuspensionsRequestBuilder {

    private Optional<? extends PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion> xGustoAPIVersion = Utils.readDefaultOrConstValue(
                            "xGustoAPIVersion",
                            "\"2025-11-15\"",
                            new TypeReference<Optional<? extends PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion>>() {});
    private String companyUuid;
    private PostCompaniesCompanyUuidSuspensionsRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PostCompaniesCompanyUuidSuspensionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PostCompaniesCompanyUuidSuspensionsRequestBuilder xGustoAPIVersion(PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.of(xGustoAPIVersion);
        return this;
    }

    public PostCompaniesCompanyUuidSuspensionsRequestBuilder xGustoAPIVersion(Optional<? extends PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    public PostCompaniesCompanyUuidSuspensionsRequestBuilder companyUuid(String companyUuid) {
        Utils.checkNotNull(companyUuid, "companyUuid");
        this.companyUuid = companyUuid;
        return this;
    }

    public PostCompaniesCompanyUuidSuspensionsRequestBuilder requestBody(PostCompaniesCompanyUuidSuspensionsRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private PostCompaniesCompanyUuidSuspensionsRequest buildRequest() {
        if (xGustoAPIVersion == null) {
            xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
        }

        PostCompaniesCompanyUuidSuspensionsRequest request = new PostCompaniesCompanyUuidSuspensionsRequest(xGustoAPIVersion,
            companyUuid,
            requestBody);

        return request;
    }

    public PostCompaniesCompanyUuidSuspensionsResponse call() {
        
        RequestOperation<PostCompaniesCompanyUuidSuspensionsRequest, PostCompaniesCompanyUuidSuspensionsResponse> operation
              = new PostCompaniesCompanyUuidSuspensions.Sync(sdkConfiguration, _headers);
        PostCompaniesCompanyUuidSuspensionsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }

    private static final LazySingletonValue<Optional<? extends PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
            new LazySingletonValue<>(
                    "xGustoAPIVersion",
                    "\"2025-11-15\"",
                    new TypeReference<Optional<? extends PostCompaniesCompanyUuidSuspensionsHeaderXGustoAPIVersion>>() {});
}
