/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PostV1CompaniesCompanyIdPeopleBatchesType
 * 
 * <p>Payment type (must be Direct Deposit)
 */
public enum PostV1CompaniesCompanyIdPeopleBatchesType {
    DIRECT_DEPOSIT("Direct Deposit");

    @JsonValue
    private final String value;

    PostV1CompaniesCompanyIdPeopleBatchesType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PostV1CompaniesCompanyIdPeopleBatchesType> fromValue(String value) {
        for (PostV1CompaniesCompanyIdPeopleBatchesType o: PostV1CompaniesCompanyIdPeopleBatchesType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

