/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.models.components.EmployeeBenefitBulkUpdateRequest;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.SpeakeasyMetadata;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest {
    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Gusto-API-Version")
    private Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion;

    /**
     * The UUID of the company benefit
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company_benefit_id")
    private String companyBenefitId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest;

    @JsonCreator
    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest(
            Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion,
            String companyBenefitId,
            EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        Utils.checkNotNull(companyBenefitId, "companyBenefitId");
        Utils.checkNotNull(employeeBenefitBulkUpdateRequest, "employeeBenefitBulkUpdateRequest");
        this.xGustoAPIVersion = xGustoAPIVersion;
        this.companyBenefitId = companyBenefitId;
        this.employeeBenefitBulkUpdateRequest = employeeBenefitBulkUpdateRequest;
    }
    
    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest(
            String companyBenefitId,
            EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest) {
        this(Optional.empty(), companyBenefitId, employeeBenefitBulkUpdateRequest);
    }

    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion() {
        return (Optional<PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion>) xGustoAPIVersion;
    }

    /**
     * The UUID of the company benefit
     */
    @JsonIgnore
    public String companyBenefitId() {
        return companyBenefitId;
    }

    @JsonIgnore
    public EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest() {
        return employeeBenefitBulkUpdateRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest withXGustoAPIVersion(PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
        return this;
    }


    /**
     * Determines the date-based API version associated with your API call. If none is provided, your
     * application's [minimum API
     * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     */
    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest withXGustoAPIVersion(Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion) {
        Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
        this.xGustoAPIVersion = xGustoAPIVersion;
        return this;
    }

    /**
     * The UUID of the company benefit
     */
    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest withCompanyBenefitId(String companyBenefitId) {
        Utils.checkNotNull(companyBenefitId, "companyBenefitId");
        this.companyBenefitId = companyBenefitId;
        return this;
    }

    public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest withEmployeeBenefitBulkUpdateRequest(EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest) {
        Utils.checkNotNull(employeeBenefitBulkUpdateRequest, "employeeBenefitBulkUpdateRequest");
        this.employeeBenefitBulkUpdateRequest = employeeBenefitBulkUpdateRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest other = (PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.xGustoAPIVersion, other.xGustoAPIVersion) &&
            Utils.enhancedDeepEquals(this.companyBenefitId, other.companyBenefitId) &&
            Utils.enhancedDeepEquals(this.employeeBenefitBulkUpdateRequest, other.employeeBenefitBulkUpdateRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            xGustoAPIVersion, companyBenefitId, employeeBenefitBulkUpdateRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest.class,
                "xGustoAPIVersion", xGustoAPIVersion,
                "companyBenefitId", companyBenefitId,
                "employeeBenefitBulkUpdateRequest", employeeBenefitBulkUpdateRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion;

        private String companyBenefitId;

        private EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = Optional.ofNullable(xGustoAPIVersion);
            return this;
        }

        /**
         * Determines the date-based API version associated with your API call. If none is provided, your
         * application's [minimum API
         * version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         */
        public Builder xGustoAPIVersion(Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion> xGustoAPIVersion) {
            Utils.checkNotNull(xGustoAPIVersion, "xGustoAPIVersion");
            this.xGustoAPIVersion = xGustoAPIVersion;
            return this;
        }


        /**
         * The UUID of the company benefit
         */
        public Builder companyBenefitId(String companyBenefitId) {
            Utils.checkNotNull(companyBenefitId, "companyBenefitId");
            this.companyBenefitId = companyBenefitId;
            return this;
        }


        public Builder employeeBenefitBulkUpdateRequest(EmployeeBenefitBulkUpdateRequest employeeBenefitBulkUpdateRequest) {
            Utils.checkNotNull(employeeBenefitBulkUpdateRequest, "employeeBenefitBulkUpdateRequest");
            this.employeeBenefitBulkUpdateRequest = employeeBenefitBulkUpdateRequest;
            return this;
        }

        public PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest build() {
            if (xGustoAPIVersion == null) {
                xGustoAPIVersion = _SINGLETON_VALUE_XGustoAPIVersion.value();
            }

            return new PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsRequest(
                xGustoAPIVersion, companyBenefitId, employeeBenefitBulkUpdateRequest);
        }


        private static final LazySingletonValue<Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion>> _SINGLETON_VALUE_XGustoAPIVersion =
                new LazySingletonValue<>(
                        "X-Gusto-API-Version",
                        "\"2025-11-15\"",
                        new TypeReference<Optional<? extends PutV1CompanyBenefitsCompanyBenefitIdEmployeeBenefitsHeaderXGustoAPIVersion>>() {});
    }
}
