/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.operations;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.RequestOperation;

import com.gusto.embedded_api_v_2025_11_15.SDKConfiguration;
import com.gusto.embedded_api_v_2025_11_15.operations.SubmitInformationRequest;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.String;

public class SubmitInformationRequestRequestBuilder {

    private String informationRequestUuid;
    private SubmitInformationRequestRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public SubmitInformationRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SubmitInformationRequestRequestBuilder informationRequestUuid(String informationRequestUuid) {
        Utils.checkNotNull(informationRequestUuid, "informationRequestUuid");
        this.informationRequestUuid = informationRequestUuid;
        return this;
    }

    public SubmitInformationRequestRequestBuilder requestBody(SubmitInformationRequestRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private SubmitInformationRequestRequest buildRequest() {

        SubmitInformationRequestRequest request = new SubmitInformationRequestRequest(informationRequestUuid,
            requestBody);

        return request;
    }

    public SubmitInformationRequestResponse call() {
        
        RequestOperation<SubmitInformationRequestRequest, SubmitInformationRequestResponse> operation
              = new SubmitInformationRequest.Sync(sdkConfiguration, _headers);
        SubmitInformationRequestRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
