/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class Benefits {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("benefit_id")
    private Optional<Long> benefitId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_contribution_amount")
    private Optional<String> companyContributionAmount;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("employee_deduction_amount")
    private Optional<String> employeeDeductionAmount;

    @JsonCreator
    public Benefits(
            @JsonProperty("benefit_id") Optional<Long> benefitId,
            @JsonProperty("company_contribution_amount") Optional<String> companyContributionAmount,
            @JsonProperty("employee_deduction_amount") Optional<String> employeeDeductionAmount) {
        Utils.checkNotNull(benefitId, "benefitId");
        Utils.checkNotNull(companyContributionAmount, "companyContributionAmount");
        Utils.checkNotNull(employeeDeductionAmount, "employeeDeductionAmount");
        this.benefitId = benefitId;
        this.companyContributionAmount = companyContributionAmount;
        this.employeeDeductionAmount = employeeDeductionAmount;
    }
    
    public Benefits() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<Long> benefitId() {
        return benefitId;
    }

    @JsonIgnore
    public Optional<String> companyContributionAmount() {
        return companyContributionAmount;
    }

    @JsonIgnore
    public Optional<String> employeeDeductionAmount() {
        return employeeDeductionAmount;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Benefits withBenefitId(long benefitId) {
        Utils.checkNotNull(benefitId, "benefitId");
        this.benefitId = Optional.ofNullable(benefitId);
        return this;
    }


    public Benefits withBenefitId(Optional<Long> benefitId) {
        Utils.checkNotNull(benefitId, "benefitId");
        this.benefitId = benefitId;
        return this;
    }

    public Benefits withCompanyContributionAmount(String companyContributionAmount) {
        Utils.checkNotNull(companyContributionAmount, "companyContributionAmount");
        this.companyContributionAmount = Optional.ofNullable(companyContributionAmount);
        return this;
    }


    public Benefits withCompanyContributionAmount(Optional<String> companyContributionAmount) {
        Utils.checkNotNull(companyContributionAmount, "companyContributionAmount");
        this.companyContributionAmount = companyContributionAmount;
        return this;
    }

    public Benefits withEmployeeDeductionAmount(String employeeDeductionAmount) {
        Utils.checkNotNull(employeeDeductionAmount, "employeeDeductionAmount");
        this.employeeDeductionAmount = Optional.ofNullable(employeeDeductionAmount);
        return this;
    }


    public Benefits withEmployeeDeductionAmount(Optional<String> employeeDeductionAmount) {
        Utils.checkNotNull(employeeDeductionAmount, "employeeDeductionAmount");
        this.employeeDeductionAmount = employeeDeductionAmount;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Benefits other = (Benefits) o;
        return 
            Utils.enhancedDeepEquals(this.benefitId, other.benefitId) &&
            Utils.enhancedDeepEquals(this.companyContributionAmount, other.companyContributionAmount) &&
            Utils.enhancedDeepEquals(this.employeeDeductionAmount, other.employeeDeductionAmount);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            benefitId, companyContributionAmount, employeeDeductionAmount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Benefits.class,
                "benefitId", benefitId,
                "companyContributionAmount", companyContributionAmount,
                "employeeDeductionAmount", employeeDeductionAmount);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Long> benefitId = Optional.empty();

        private Optional<String> companyContributionAmount = Optional.empty();

        private Optional<String> employeeDeductionAmount = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder benefitId(long benefitId) {
            Utils.checkNotNull(benefitId, "benefitId");
            this.benefitId = Optional.ofNullable(benefitId);
            return this;
        }

        public Builder benefitId(Optional<Long> benefitId) {
            Utils.checkNotNull(benefitId, "benefitId");
            this.benefitId = benefitId;
            return this;
        }


        public Builder companyContributionAmount(String companyContributionAmount) {
            Utils.checkNotNull(companyContributionAmount, "companyContributionAmount");
            this.companyContributionAmount = Optional.ofNullable(companyContributionAmount);
            return this;
        }

        public Builder companyContributionAmount(Optional<String> companyContributionAmount) {
            Utils.checkNotNull(companyContributionAmount, "companyContributionAmount");
            this.companyContributionAmount = companyContributionAmount;
            return this;
        }


        public Builder employeeDeductionAmount(String employeeDeductionAmount) {
            Utils.checkNotNull(employeeDeductionAmount, "employeeDeductionAmount");
            this.employeeDeductionAmount = Optional.ofNullable(employeeDeductionAmount);
            return this;
        }

        public Builder employeeDeductionAmount(Optional<String> employeeDeductionAmount) {
            Utils.checkNotNull(employeeDeductionAmount, "employeeDeductionAmount");
            this.employeeDeductionAmount = employeeDeductionAmount;
            return this;
        }

        public Benefits build() {

            return new Benefits(
                benefitId, companyContributionAmount, employeeDeductionAmount);
        }

    }
}
