/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class CompanyCustomFieldList {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_fields")
    private Optional<? extends List<CompanyCustomField>> customFields;

    @JsonCreator
    public CompanyCustomFieldList(
            @JsonProperty("custom_fields") Optional<? extends List<CompanyCustomField>> customFields) {
        Utils.checkNotNull(customFields, "customFields");
        this.customFields = customFields;
    }
    
    public CompanyCustomFieldList() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<CompanyCustomField>> customFields() {
        return (Optional<List<CompanyCustomField>>) customFields;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CompanyCustomFieldList withCustomFields(List<CompanyCustomField> customFields) {
        Utils.checkNotNull(customFields, "customFields");
        this.customFields = Optional.ofNullable(customFields);
        return this;
    }


    public CompanyCustomFieldList withCustomFields(Optional<? extends List<CompanyCustomField>> customFields) {
        Utils.checkNotNull(customFields, "customFields");
        this.customFields = customFields;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompanyCustomFieldList other = (CompanyCustomFieldList) o;
        return 
            Utils.enhancedDeepEquals(this.customFields, other.customFields);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            customFields);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompanyCustomFieldList.class,
                "customFields", customFields);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<CompanyCustomField>> customFields = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder customFields(List<CompanyCustomField> customFields) {
            Utils.checkNotNull(customFields, "customFields");
            this.customFields = Optional.ofNullable(customFields);
            return this;
        }

        public Builder customFields(Optional<? extends List<CompanyCustomField>> customFields) {
            Utils.checkNotNull(customFields, "customFields");
            this.customFields = customFields;
            return this;
        }

        public CompanyCustomFieldList build() {

            return new CompanyCustomFieldList(
                customFields);
        }

    }
}
