/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum ContractorPaymentBodyPaymentMethod {
    DIRECT_DEPOSIT("Direct Deposit"),
    CHECK("Check"),
    HISTORICAL_PAYMENT("Historical Payment");

    @JsonValue
    private final String value;

    ContractorPaymentBodyPaymentMethod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ContractorPaymentBodyPaymentMethod> fromValue(String value) {
        for (ContractorPaymentBodyPaymentMethod o: ContractorPaymentBodyPaymentMethod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

