/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;


public class ContributionExclusionUpdateRequest {
    /**
     * The list of contribution exclusions to update
     */
    @JsonProperty("contribution_exclusions")
    private List<ContributionExclusion> contributionExclusions;

    @JsonCreator
    public ContributionExclusionUpdateRequest(
            @JsonProperty("contribution_exclusions") List<ContributionExclusion> contributionExclusions) {
        Utils.checkNotNull(contributionExclusions, "contributionExclusions");
        this.contributionExclusions = contributionExclusions;
    }

    /**
     * The list of contribution exclusions to update
     */
    @JsonIgnore
    public List<ContributionExclusion> contributionExclusions() {
        return contributionExclusions;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The list of contribution exclusions to update
     */
    public ContributionExclusionUpdateRequest withContributionExclusions(List<ContributionExclusion> contributionExclusions) {
        Utils.checkNotNull(contributionExclusions, "contributionExclusions");
        this.contributionExclusions = contributionExclusions;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContributionExclusionUpdateRequest other = (ContributionExclusionUpdateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.contributionExclusions, other.contributionExclusions);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contributionExclusions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ContributionExclusionUpdateRequest.class,
                "contributionExclusions", contributionExclusions);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<ContributionExclusion> contributionExclusions;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The list of contribution exclusions to update
         */
        public Builder contributionExclusions(List<ContributionExclusion> contributionExclusions) {
            Utils.checkNotNull(contributionExclusions, "contributionExclusions");
            this.contributionExclusions = contributionExclusions;
            return this;
        }

        public ContributionExclusionUpdateRequest build() {

            return new ContributionExclusionUpdateRequest(
                contributionExclusions);
        }

    }
}
