/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ContractorBankAccountCreateRequestBodyAccountType
 * 
 * <p>Bank account type
 */
public enum ContractorBankAccountCreateRequestBodyAccountType {
    CHECKING("Checking"),
    SAVINGS("Savings");

    @JsonValue
    private final String value;

    ContractorBankAccountCreateRequestBodyAccountType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ContractorBankAccountCreateRequestBodyAccountType> fromValue(String value) {
        for (ContractorBankAccountCreateRequestBodyAccountType o: ContractorBankAccountCreateRequestBodyAccountType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

