/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ContractorType
 * 
 * <p>The contractor's type, either "Individual" or "Business".
 */
public enum ContractorType {
    INDIVIDUAL("Individual"),
    BUSINESS("Business");

    @JsonValue
    private final String value;

    ContractorType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ContractorType> fromValue(String value) {
        for (ContractorType o: ContractorType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

