/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * EmployeeBenefitForCompanyBenefit
 * 
 * <p>The representation of an employee benefit for a company benefit.
 */
public class EmployeeBenefitForCompanyBenefit {
    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    private Optional<String> version;

    /**
     * Whether the employee benefit is active.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("active")
    private Optional<Boolean> active;

    /**
     * The amount to be deducted, per pay period, from the employee's pay.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("employee_deduction")
    private Optional<String> employeeDeduction;

    /**
     * Whether the employee deduction amount should be treated as a percentage to be deducted from each
     * payroll.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deduct_as_percentage")
    private Optional<Boolean> deductAsPercentage;

    /**
     * The maximum employee deduction amount per year. A null value signifies no limit.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("employee_deduction_annual_maximum")
    private JsonNullable<String> employeeDeductionAnnualMaximum;

    /**
     * An object representing the type and value of the company contribution.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contribution")
    private Optional<? extends EmployeeBenefitForCompanyBenefitContribution> contribution;

    /**
     * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
     * is always true.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("elective")
    private Optional<Boolean> elective;

    /**
     * The maximum company contribution amount per year. A null value signifies no limit.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_contribution_annual_maximum")
    private JsonNullable<String> companyContributionAnnualMaximum;

    /**
     * Some benefits require additional information to determine their limit.
     * 
     * <p>`Family` and `Individual` are applicable to HSA benefit.
     * 
     * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
     * benefit.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit_option")
    private JsonNullable<String> limitOption;

    /**
     * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
     * this value for employees over 50.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("catch_up")
    private JsonNullable<Boolean> catchUp;

    /**
     * Identifier for a 401(k) loan assigned by the 401(k) provider
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("retirement_loan_identifier")
    private JsonNullable<String> retirementLoanIdentifier;

    /**
     * The amount that the employee is insured for. Note: company contribution cannot be present if
     * coverage amount is set.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("coverage_amount")
    private JsonNullable<String> coverageAmount;

    /**
     * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
     * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
     * ignored.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deduction_reduces_taxable_income")
    private JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome;

    /**
     * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
     * benefits. Note: cannot be set if coverage amount is also set.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("coverage_salary_multiplier")
    private JsonNullable<String> coverageSalaryMultiplier;

    /**
     * The amount to be paid, per pay period, by the company. This field will not appear for tiered
     * contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_contribution")
    @Deprecated
    private Optional<String> companyContribution;

    /**
     * Whether the company_contribution value should be treated as a percentage to be added to each
     * payroll. This field will not appear for tiered contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contribute_as_percentage")
    @Deprecated
    private Optional<Boolean> contributeAsPercentage;

    /**
     * The date the employee benefit will start.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("effective_date")
    private Optional<LocalDate> effectiveDate;

    /**
     * The date the employee benefit will expire. A null value indicates the benefit will not expire.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expiration_date")
    private JsonNullable<LocalDate> expirationDate;

    /**
     * The UUID of the employee to which the benefit belongs.
     */
    @JsonProperty("employee_uuid")
    private String employeeUuid;

    /**
     * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uuid")
    private Optional<String> uuid;

    /**
     * The action to perform on the employee benefit. Required for creating/updating an effective dated
     * employee benefit.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    private Optional<? extends Action> action;


    @JsonIgnore
    private Map<String, Object> additionalProperties;

    @JsonCreator
    public EmployeeBenefitForCompanyBenefit(
            @JsonProperty("version") Optional<String> version,
            @JsonProperty("active") Optional<Boolean> active,
            @JsonProperty("employee_deduction") Optional<String> employeeDeduction,
            @JsonProperty("deduct_as_percentage") Optional<Boolean> deductAsPercentage,
            @JsonProperty("employee_deduction_annual_maximum") JsonNullable<String> employeeDeductionAnnualMaximum,
            @JsonProperty("contribution") Optional<? extends EmployeeBenefitForCompanyBenefitContribution> contribution,
            @JsonProperty("elective") Optional<Boolean> elective,
            @JsonProperty("company_contribution_annual_maximum") JsonNullable<String> companyContributionAnnualMaximum,
            @JsonProperty("limit_option") JsonNullable<String> limitOption,
            @JsonProperty("catch_up") JsonNullable<Boolean> catchUp,
            @JsonProperty("retirement_loan_identifier") JsonNullable<String> retirementLoanIdentifier,
            @JsonProperty("coverage_amount") JsonNullable<String> coverageAmount,
            @JsonProperty("deduction_reduces_taxable_income") JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome,
            @JsonProperty("coverage_salary_multiplier") JsonNullable<String> coverageSalaryMultiplier,
            @JsonProperty("company_contribution") Optional<String> companyContribution,
            @JsonProperty("contribute_as_percentage") Optional<Boolean> contributeAsPercentage,
            @JsonProperty("effective_date") Optional<LocalDate> effectiveDate,
            @JsonProperty("expiration_date") JsonNullable<LocalDate> expirationDate,
            @JsonProperty("employee_uuid") String employeeUuid,
            @JsonProperty("uuid") Optional<String> uuid,
            @JsonProperty("action") Optional<? extends Action> action) {
        Utils.checkNotNull(version, "version");
        Utils.checkNotNull(active, "active");
        Utils.checkNotNull(employeeDeduction, "employeeDeduction");
        Utils.checkNotNull(deductAsPercentage, "deductAsPercentage");
        Utils.checkNotNull(employeeDeductionAnnualMaximum, "employeeDeductionAnnualMaximum");
        Utils.checkNotNull(contribution, "contribution");
        Utils.checkNotNull(elective, "elective");
        Utils.checkNotNull(companyContributionAnnualMaximum, "companyContributionAnnualMaximum");
        Utils.checkNotNull(limitOption, "limitOption");
        Utils.checkNotNull(catchUp, "catchUp");
        Utils.checkNotNull(retirementLoanIdentifier, "retirementLoanIdentifier");
        Utils.checkNotNull(coverageAmount, "coverageAmount");
        Utils.checkNotNull(deductionReducesTaxableIncome, "deductionReducesTaxableIncome");
        Utils.checkNotNull(coverageSalaryMultiplier, "coverageSalaryMultiplier");
        Utils.checkNotNull(companyContribution, "companyContribution");
        Utils.checkNotNull(contributeAsPercentage, "contributeAsPercentage");
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        Utils.checkNotNull(expirationDate, "expirationDate");
        Utils.checkNotNull(employeeUuid, "employeeUuid");
        Utils.checkNotNull(uuid, "uuid");
        Utils.checkNotNull(action, "action");
        this.version = version;
        this.active = active;
        this.employeeDeduction = employeeDeduction;
        this.deductAsPercentage = deductAsPercentage;
        this.employeeDeductionAnnualMaximum = employeeDeductionAnnualMaximum;
        this.contribution = contribution;
        this.elective = elective;
        this.companyContributionAnnualMaximum = companyContributionAnnualMaximum;
        this.limitOption = limitOption;
        this.catchUp = catchUp;
        this.retirementLoanIdentifier = retirementLoanIdentifier;
        this.coverageAmount = coverageAmount;
        this.deductionReducesTaxableIncome = deductionReducesTaxableIncome;
        this.coverageSalaryMultiplier = coverageSalaryMultiplier;
        this.companyContribution = companyContribution;
        this.contributeAsPercentage = contributeAsPercentage;
        this.effectiveDate = effectiveDate;
        this.expirationDate = expirationDate;
        this.employeeUuid = employeeUuid;
        this.uuid = uuid;
        this.action = action;
        this.additionalProperties = new HashMap<>();
    }
    
    public EmployeeBenefitForCompanyBenefit(
            String employeeUuid) {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), JsonNullable.undefined(), Optional.empty(),
            Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(),
            Optional.empty(), Optional.empty(), JsonNullable.undefined(),
            employeeUuid, Optional.empty(), Optional.empty());
    }

    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    @JsonIgnore
    public Optional<String> version() {
        return version;
    }

    /**
     * Whether the employee benefit is active.
     */
    @JsonIgnore
    public Optional<Boolean> active() {
        return active;
    }

    /**
     * The amount to be deducted, per pay period, from the employee's pay.
     */
    @JsonIgnore
    public Optional<String> employeeDeduction() {
        return employeeDeduction;
    }

    /**
     * Whether the employee deduction amount should be treated as a percentage to be deducted from each
     * payroll.
     */
    @JsonIgnore
    public Optional<Boolean> deductAsPercentage() {
        return deductAsPercentage;
    }

    /**
     * The maximum employee deduction amount per year. A null value signifies no limit.
     */
    @JsonIgnore
    public JsonNullable<String> employeeDeductionAnnualMaximum() {
        return employeeDeductionAnnualMaximum;
    }

    /**
     * An object representing the type and value of the company contribution.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EmployeeBenefitForCompanyBenefitContribution> contribution() {
        return (Optional<EmployeeBenefitForCompanyBenefitContribution>) contribution;
    }

    /**
     * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
     * is always true.
     */
    @JsonIgnore
    public Optional<Boolean> elective() {
        return elective;
    }

    /**
     * The maximum company contribution amount per year. A null value signifies no limit.
     */
    @JsonIgnore
    public JsonNullable<String> companyContributionAnnualMaximum() {
        return companyContributionAnnualMaximum;
    }

    /**
     * Some benefits require additional information to determine their limit.
     * 
     * <p>`Family` and `Individual` are applicable to HSA benefit.
     * 
     * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
     * benefit.
     */
    @JsonIgnore
    public JsonNullable<String> limitOption() {
        return limitOption;
    }

    /**
     * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
     * this value for employees over 50.
     */
    @JsonIgnore
    public JsonNullable<Boolean> catchUp() {
        return catchUp;
    }

    /**
     * Identifier for a 401(k) loan assigned by the 401(k) provider
     */
    @JsonIgnore
    public JsonNullable<String> retirementLoanIdentifier() {
        return retirementLoanIdentifier;
    }

    /**
     * The amount that the employee is insured for. Note: company contribution cannot be present if
     * coverage amount is set.
     */
    @JsonIgnore
    public JsonNullable<String> coverageAmount() {
        return coverageAmount;
    }

    /**
     * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
     * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
     * ignored.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome() {
        return (JsonNullable<EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome>) deductionReducesTaxableIncome;
    }

    /**
     * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
     * benefits. Note: cannot be set if coverage amount is also set.
     */
    @JsonIgnore
    public JsonNullable<String> coverageSalaryMultiplier() {
        return coverageSalaryMultiplier;
    }

    /**
     * The amount to be paid, per pay period, by the company. This field will not appear for tiered
     * contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    @JsonIgnore
    public Optional<String> companyContribution() {
        return companyContribution;
    }

    /**
     * Whether the company_contribution value should be treated as a percentage to be added to each
     * payroll. This field will not appear for tiered contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    @JsonIgnore
    public Optional<Boolean> contributeAsPercentage() {
        return contributeAsPercentage;
    }

    /**
     * The date the employee benefit will start.
     */
    @JsonIgnore
    public Optional<LocalDate> effectiveDate() {
        return effectiveDate;
    }

    /**
     * The date the employee benefit will expire. A null value indicates the benefit will not expire.
     */
    @JsonIgnore
    public JsonNullable<LocalDate> expirationDate() {
        return expirationDate;
    }

    /**
     * The UUID of the employee to which the benefit belongs.
     */
    @JsonIgnore
    public String employeeUuid() {
        return employeeUuid;
    }

    /**
     * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
     */
    @JsonIgnore
    public Optional<String> uuid() {
        return uuid;
    }

    /**
     * The action to perform on the employee benefit. Required for creating/updating an effective dated
     * employee benefit.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Action> action() {
        return (Optional<Action>) action;
    }

    @JsonAnyGetter
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    public EmployeeBenefitForCompanyBenefit withVersion(String version) {
        Utils.checkNotNull(version, "version");
        this.version = Optional.ofNullable(version);
        return this;
    }


    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    public EmployeeBenefitForCompanyBenefit withVersion(Optional<String> version) {
        Utils.checkNotNull(version, "version");
        this.version = version;
        return this;
    }

    /**
     * Whether the employee benefit is active.
     */
    public EmployeeBenefitForCompanyBenefit withActive(boolean active) {
        Utils.checkNotNull(active, "active");
        this.active = Optional.ofNullable(active);
        return this;
    }


    /**
     * Whether the employee benefit is active.
     */
    public EmployeeBenefitForCompanyBenefit withActive(Optional<Boolean> active) {
        Utils.checkNotNull(active, "active");
        this.active = active;
        return this;
    }

    /**
     * The amount to be deducted, per pay period, from the employee's pay.
     */
    public EmployeeBenefitForCompanyBenefit withEmployeeDeduction(String employeeDeduction) {
        Utils.checkNotNull(employeeDeduction, "employeeDeduction");
        this.employeeDeduction = Optional.ofNullable(employeeDeduction);
        return this;
    }


    /**
     * The amount to be deducted, per pay period, from the employee's pay.
     */
    public EmployeeBenefitForCompanyBenefit withEmployeeDeduction(Optional<String> employeeDeduction) {
        Utils.checkNotNull(employeeDeduction, "employeeDeduction");
        this.employeeDeduction = employeeDeduction;
        return this;
    }

    /**
     * Whether the employee deduction amount should be treated as a percentage to be deducted from each
     * payroll.
     */
    public EmployeeBenefitForCompanyBenefit withDeductAsPercentage(boolean deductAsPercentage) {
        Utils.checkNotNull(deductAsPercentage, "deductAsPercentage");
        this.deductAsPercentage = Optional.ofNullable(deductAsPercentage);
        return this;
    }


    /**
     * Whether the employee deduction amount should be treated as a percentage to be deducted from each
     * payroll.
     */
    public EmployeeBenefitForCompanyBenefit withDeductAsPercentage(Optional<Boolean> deductAsPercentage) {
        Utils.checkNotNull(deductAsPercentage, "deductAsPercentage");
        this.deductAsPercentage = deductAsPercentage;
        return this;
    }

    /**
     * The maximum employee deduction amount per year. A null value signifies no limit.
     */
    public EmployeeBenefitForCompanyBenefit withEmployeeDeductionAnnualMaximum(String employeeDeductionAnnualMaximum) {
        Utils.checkNotNull(employeeDeductionAnnualMaximum, "employeeDeductionAnnualMaximum");
        this.employeeDeductionAnnualMaximum = JsonNullable.of(employeeDeductionAnnualMaximum);
        return this;
    }

    /**
     * The maximum employee deduction amount per year. A null value signifies no limit.
     */
    public EmployeeBenefitForCompanyBenefit withEmployeeDeductionAnnualMaximum(JsonNullable<String> employeeDeductionAnnualMaximum) {
        Utils.checkNotNull(employeeDeductionAnnualMaximum, "employeeDeductionAnnualMaximum");
        this.employeeDeductionAnnualMaximum = employeeDeductionAnnualMaximum;
        return this;
    }

    /**
     * An object representing the type and value of the company contribution.
     */
    public EmployeeBenefitForCompanyBenefit withContribution(EmployeeBenefitForCompanyBenefitContribution contribution) {
        Utils.checkNotNull(contribution, "contribution");
        this.contribution = Optional.ofNullable(contribution);
        return this;
    }


    /**
     * An object representing the type and value of the company contribution.
     */
    public EmployeeBenefitForCompanyBenefit withContribution(Optional<? extends EmployeeBenefitForCompanyBenefitContribution> contribution) {
        Utils.checkNotNull(contribution, "contribution");
        this.contribution = contribution;
        return this;
    }

    /**
     * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
     * is always true.
     */
    public EmployeeBenefitForCompanyBenefit withElective(boolean elective) {
        Utils.checkNotNull(elective, "elective");
        this.elective = Optional.ofNullable(elective);
        return this;
    }


    /**
     * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
     * is always true.
     */
    public EmployeeBenefitForCompanyBenefit withElective(Optional<Boolean> elective) {
        Utils.checkNotNull(elective, "elective");
        this.elective = elective;
        return this;
    }

    /**
     * The maximum company contribution amount per year. A null value signifies no limit.
     */
    public EmployeeBenefitForCompanyBenefit withCompanyContributionAnnualMaximum(String companyContributionAnnualMaximum) {
        Utils.checkNotNull(companyContributionAnnualMaximum, "companyContributionAnnualMaximum");
        this.companyContributionAnnualMaximum = JsonNullable.of(companyContributionAnnualMaximum);
        return this;
    }

    /**
     * The maximum company contribution amount per year. A null value signifies no limit.
     */
    public EmployeeBenefitForCompanyBenefit withCompanyContributionAnnualMaximum(JsonNullable<String> companyContributionAnnualMaximum) {
        Utils.checkNotNull(companyContributionAnnualMaximum, "companyContributionAnnualMaximum");
        this.companyContributionAnnualMaximum = companyContributionAnnualMaximum;
        return this;
    }

    /**
     * Some benefits require additional information to determine their limit.
     * 
     * <p>`Family` and `Individual` are applicable to HSA benefit.
     * 
     * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
     * benefit.
     */
    public EmployeeBenefitForCompanyBenefit withLimitOption(String limitOption) {
        Utils.checkNotNull(limitOption, "limitOption");
        this.limitOption = JsonNullable.of(limitOption);
        return this;
    }

    /**
     * Some benefits require additional information to determine their limit.
     * 
     * <p>`Family` and `Individual` are applicable to HSA benefit.
     * 
     * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
     * benefit.
     */
    public EmployeeBenefitForCompanyBenefit withLimitOption(JsonNullable<String> limitOption) {
        Utils.checkNotNull(limitOption, "limitOption");
        this.limitOption = limitOption;
        return this;
    }

    /**
     * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
     * this value for employees over 50.
     */
    public EmployeeBenefitForCompanyBenefit withCatchUp(boolean catchUp) {
        Utils.checkNotNull(catchUp, "catchUp");
        this.catchUp = JsonNullable.of(catchUp);
        return this;
    }

    /**
     * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
     * this value for employees over 50.
     */
    public EmployeeBenefitForCompanyBenefit withCatchUp(JsonNullable<Boolean> catchUp) {
        Utils.checkNotNull(catchUp, "catchUp");
        this.catchUp = catchUp;
        return this;
    }

    /**
     * Identifier for a 401(k) loan assigned by the 401(k) provider
     */
    public EmployeeBenefitForCompanyBenefit withRetirementLoanIdentifier(String retirementLoanIdentifier) {
        Utils.checkNotNull(retirementLoanIdentifier, "retirementLoanIdentifier");
        this.retirementLoanIdentifier = JsonNullable.of(retirementLoanIdentifier);
        return this;
    }

    /**
     * Identifier for a 401(k) loan assigned by the 401(k) provider
     */
    public EmployeeBenefitForCompanyBenefit withRetirementLoanIdentifier(JsonNullable<String> retirementLoanIdentifier) {
        Utils.checkNotNull(retirementLoanIdentifier, "retirementLoanIdentifier");
        this.retirementLoanIdentifier = retirementLoanIdentifier;
        return this;
    }

    /**
     * The amount that the employee is insured for. Note: company contribution cannot be present if
     * coverage amount is set.
     */
    public EmployeeBenefitForCompanyBenefit withCoverageAmount(String coverageAmount) {
        Utils.checkNotNull(coverageAmount, "coverageAmount");
        this.coverageAmount = JsonNullable.of(coverageAmount);
        return this;
    }

    /**
     * The amount that the employee is insured for. Note: company contribution cannot be present if
     * coverage amount is set.
     */
    public EmployeeBenefitForCompanyBenefit withCoverageAmount(JsonNullable<String> coverageAmount) {
        Utils.checkNotNull(coverageAmount, "coverageAmount");
        this.coverageAmount = coverageAmount;
        return this;
    }

    /**
     * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
     * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
     * ignored.
     */
    public EmployeeBenefitForCompanyBenefit withDeductionReducesTaxableIncome(EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome deductionReducesTaxableIncome) {
        Utils.checkNotNull(deductionReducesTaxableIncome, "deductionReducesTaxableIncome");
        this.deductionReducesTaxableIncome = JsonNullable.of(deductionReducesTaxableIncome);
        return this;
    }

    /**
     * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
     * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
     * ignored.
     */
    public EmployeeBenefitForCompanyBenefit withDeductionReducesTaxableIncome(JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome) {
        Utils.checkNotNull(deductionReducesTaxableIncome, "deductionReducesTaxableIncome");
        this.deductionReducesTaxableIncome = deductionReducesTaxableIncome;
        return this;
    }

    /**
     * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
     * benefits. Note: cannot be set if coverage amount is also set.
     */
    public EmployeeBenefitForCompanyBenefit withCoverageSalaryMultiplier(String coverageSalaryMultiplier) {
        Utils.checkNotNull(coverageSalaryMultiplier, "coverageSalaryMultiplier");
        this.coverageSalaryMultiplier = JsonNullable.of(coverageSalaryMultiplier);
        return this;
    }

    /**
     * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
     * benefits. Note: cannot be set if coverage amount is also set.
     */
    public EmployeeBenefitForCompanyBenefit withCoverageSalaryMultiplier(JsonNullable<String> coverageSalaryMultiplier) {
        Utils.checkNotNull(coverageSalaryMultiplier, "coverageSalaryMultiplier");
        this.coverageSalaryMultiplier = coverageSalaryMultiplier;
        return this;
    }

    /**
     * The amount to be paid, per pay period, by the company. This field will not appear for tiered
     * contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public EmployeeBenefitForCompanyBenefit withCompanyContribution(String companyContribution) {
        Utils.checkNotNull(companyContribution, "companyContribution");
        this.companyContribution = Optional.ofNullable(companyContribution);
        return this;
    }


    /**
     * The amount to be paid, per pay period, by the company. This field will not appear for tiered
     * contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public EmployeeBenefitForCompanyBenefit withCompanyContribution(Optional<String> companyContribution) {
        Utils.checkNotNull(companyContribution, "companyContribution");
        this.companyContribution = companyContribution;
        return this;
    }

    /**
     * Whether the company_contribution value should be treated as a percentage to be added to each
     * payroll. This field will not appear for tiered contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public EmployeeBenefitForCompanyBenefit withContributeAsPercentage(boolean contributeAsPercentage) {
        Utils.checkNotNull(contributeAsPercentage, "contributeAsPercentage");
        this.contributeAsPercentage = Optional.ofNullable(contributeAsPercentage);
        return this;
    }


    /**
     * Whether the company_contribution value should be treated as a percentage to be added to each
     * payroll. This field will not appear for tiered contribution types.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public EmployeeBenefitForCompanyBenefit withContributeAsPercentage(Optional<Boolean> contributeAsPercentage) {
        Utils.checkNotNull(contributeAsPercentage, "contributeAsPercentage");
        this.contributeAsPercentage = contributeAsPercentage;
        return this;
    }

    /**
     * The date the employee benefit will start.
     */
    public EmployeeBenefitForCompanyBenefit withEffectiveDate(LocalDate effectiveDate) {
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        this.effectiveDate = Optional.ofNullable(effectiveDate);
        return this;
    }


    /**
     * The date the employee benefit will start.
     */
    public EmployeeBenefitForCompanyBenefit withEffectiveDate(Optional<LocalDate> effectiveDate) {
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        this.effectiveDate = effectiveDate;
        return this;
    }

    /**
     * The date the employee benefit will expire. A null value indicates the benefit will not expire.
     */
    public EmployeeBenefitForCompanyBenefit withExpirationDate(LocalDate expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = JsonNullable.of(expirationDate);
        return this;
    }

    /**
     * The date the employee benefit will expire. A null value indicates the benefit will not expire.
     */
    public EmployeeBenefitForCompanyBenefit withExpirationDate(JsonNullable<LocalDate> expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * The UUID of the employee to which the benefit belongs.
     */
    public EmployeeBenefitForCompanyBenefit withEmployeeUuid(String employeeUuid) {
        Utils.checkNotNull(employeeUuid, "employeeUuid");
        this.employeeUuid = employeeUuid;
        return this;
    }

    /**
     * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
     */
    public EmployeeBenefitForCompanyBenefit withUuid(String uuid) {
        Utils.checkNotNull(uuid, "uuid");
        this.uuid = Optional.ofNullable(uuid);
        return this;
    }


    /**
     * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
     */
    public EmployeeBenefitForCompanyBenefit withUuid(Optional<String> uuid) {
        Utils.checkNotNull(uuid, "uuid");
        this.uuid = uuid;
        return this;
    }

    /**
     * The action to perform on the employee benefit. Required for creating/updating an effective dated
     * employee benefit.
     */
    public EmployeeBenefitForCompanyBenefit withAction(Action action) {
        Utils.checkNotNull(action, "action");
        this.action = Optional.ofNullable(action);
        return this;
    }


    /**
     * The action to perform on the employee benefit. Required for creating/updating an effective dated
     * employee benefit.
     */
    public EmployeeBenefitForCompanyBenefit withAction(Optional<? extends Action> action) {
        Utils.checkNotNull(action, "action");
        this.action = action;
        return this;
    }

    @JsonAnySetter
    public EmployeeBenefitForCompanyBenefit withAdditionalProperty(String key, Object value) {
        // note that value can be null because of the way JsonAnySetter works
        Utils.checkNotNull(key, "key");
        additionalProperties.put(key, value); 
        return this;
    }
    public EmployeeBenefitForCompanyBenefit withAdditionalProperties(Map<String, Object> additionalProperties) {
        Utils.checkNotNull(additionalProperties, "additionalProperties");
        this.additionalProperties = additionalProperties;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EmployeeBenefitForCompanyBenefit other = (EmployeeBenefitForCompanyBenefit) o;
        return 
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.active, other.active) &&
            Utils.enhancedDeepEquals(this.employeeDeduction, other.employeeDeduction) &&
            Utils.enhancedDeepEquals(this.deductAsPercentage, other.deductAsPercentage) &&
            Utils.enhancedDeepEquals(this.employeeDeductionAnnualMaximum, other.employeeDeductionAnnualMaximum) &&
            Utils.enhancedDeepEquals(this.contribution, other.contribution) &&
            Utils.enhancedDeepEquals(this.elective, other.elective) &&
            Utils.enhancedDeepEquals(this.companyContributionAnnualMaximum, other.companyContributionAnnualMaximum) &&
            Utils.enhancedDeepEquals(this.limitOption, other.limitOption) &&
            Utils.enhancedDeepEquals(this.catchUp, other.catchUp) &&
            Utils.enhancedDeepEquals(this.retirementLoanIdentifier, other.retirementLoanIdentifier) &&
            Utils.enhancedDeepEquals(this.coverageAmount, other.coverageAmount) &&
            Utils.enhancedDeepEquals(this.deductionReducesTaxableIncome, other.deductionReducesTaxableIncome) &&
            Utils.enhancedDeepEquals(this.coverageSalaryMultiplier, other.coverageSalaryMultiplier) &&
            Utils.enhancedDeepEquals(this.companyContribution, other.companyContribution) &&
            Utils.enhancedDeepEquals(this.contributeAsPercentage, other.contributeAsPercentage) &&
            Utils.enhancedDeepEquals(this.effectiveDate, other.effectiveDate) &&
            Utils.enhancedDeepEquals(this.expirationDate, other.expirationDate) &&
            Utils.enhancedDeepEquals(this.employeeUuid, other.employeeUuid) &&
            Utils.enhancedDeepEquals(this.uuid, other.uuid) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.additionalProperties, other.additionalProperties);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            version, active, employeeDeduction,
            deductAsPercentage, employeeDeductionAnnualMaximum, contribution,
            elective, companyContributionAnnualMaximum, limitOption,
            catchUp, retirementLoanIdentifier, coverageAmount,
            deductionReducesTaxableIncome, coverageSalaryMultiplier, companyContribution,
            contributeAsPercentage, effectiveDate, expirationDate,
            employeeUuid, uuid, action,
            additionalProperties);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EmployeeBenefitForCompanyBenefit.class,
                "version", version,
                "active", active,
                "employeeDeduction", employeeDeduction,
                "deductAsPercentage", deductAsPercentage,
                "employeeDeductionAnnualMaximum", employeeDeductionAnnualMaximum,
                "contribution", contribution,
                "elective", elective,
                "companyContributionAnnualMaximum", companyContributionAnnualMaximum,
                "limitOption", limitOption,
                "catchUp", catchUp,
                "retirementLoanIdentifier", retirementLoanIdentifier,
                "coverageAmount", coverageAmount,
                "deductionReducesTaxableIncome", deductionReducesTaxableIncome,
                "coverageSalaryMultiplier", coverageSalaryMultiplier,
                "companyContribution", companyContribution,
                "contributeAsPercentage", contributeAsPercentage,
                "effectiveDate", effectiveDate,
                "expirationDate", expirationDate,
                "employeeUuid", employeeUuid,
                "uuid", uuid,
                "action", action,
                "additionalProperties", additionalProperties);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> version = Optional.empty();

        private Optional<Boolean> active;

        private Optional<String> employeeDeduction;

        private Optional<Boolean> deductAsPercentage;

        private JsonNullable<String> employeeDeductionAnnualMaximum = JsonNullable.undefined();

        private Optional<? extends EmployeeBenefitForCompanyBenefitContribution> contribution = Optional.empty();

        private Optional<Boolean> elective;

        private JsonNullable<String> companyContributionAnnualMaximum = JsonNullable.undefined();

        private JsonNullable<String> limitOption = JsonNullable.undefined();

        private JsonNullable<Boolean> catchUp;

        private JsonNullable<String> retirementLoanIdentifier = JsonNullable.undefined();

        private JsonNullable<String> coverageAmount = JsonNullable.undefined();

        private JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome;

        private JsonNullable<String> coverageSalaryMultiplier;

        @Deprecated
        private Optional<String> companyContribution;

        @Deprecated
        private Optional<Boolean> contributeAsPercentage;

        private Optional<LocalDate> effectiveDate = Optional.empty();

        private JsonNullable<LocalDate> expirationDate = JsonNullable.undefined();

        private String employeeUuid;

        private Optional<String> uuid = Optional.empty();

        private Optional<? extends Action> action = Optional.empty();

        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The current version of the object. See the [versioning
         * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
         * field.
         */
        public Builder version(String version) {
            Utils.checkNotNull(version, "version");
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * The current version of the object. See the [versioning
         * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
         * field.
         */
        public Builder version(Optional<String> version) {
            Utils.checkNotNull(version, "version");
            this.version = version;
            return this;
        }


        /**
         * Whether the employee benefit is active.
         */
        public Builder active(boolean active) {
            Utils.checkNotNull(active, "active");
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * Whether the employee benefit is active.
         */
        public Builder active(Optional<Boolean> active) {
            Utils.checkNotNull(active, "active");
            this.active = active;
            return this;
        }


        /**
         * The amount to be deducted, per pay period, from the employee's pay.
         */
        public Builder employeeDeduction(String employeeDeduction) {
            Utils.checkNotNull(employeeDeduction, "employeeDeduction");
            this.employeeDeduction = Optional.ofNullable(employeeDeduction);
            return this;
        }

        /**
         * The amount to be deducted, per pay period, from the employee's pay.
         */
        public Builder employeeDeduction(Optional<String> employeeDeduction) {
            Utils.checkNotNull(employeeDeduction, "employeeDeduction");
            this.employeeDeduction = employeeDeduction;
            return this;
        }


        /**
         * Whether the employee deduction amount should be treated as a percentage to be deducted from each
         * payroll.
         */
        public Builder deductAsPercentage(boolean deductAsPercentage) {
            Utils.checkNotNull(deductAsPercentage, "deductAsPercentage");
            this.deductAsPercentage = Optional.ofNullable(deductAsPercentage);
            return this;
        }

        /**
         * Whether the employee deduction amount should be treated as a percentage to be deducted from each
         * payroll.
         */
        public Builder deductAsPercentage(Optional<Boolean> deductAsPercentage) {
            Utils.checkNotNull(deductAsPercentage, "deductAsPercentage");
            this.deductAsPercentage = deductAsPercentage;
            return this;
        }


        /**
         * The maximum employee deduction amount per year. A null value signifies no limit.
         */
        public Builder employeeDeductionAnnualMaximum(String employeeDeductionAnnualMaximum) {
            Utils.checkNotNull(employeeDeductionAnnualMaximum, "employeeDeductionAnnualMaximum");
            this.employeeDeductionAnnualMaximum = JsonNullable.of(employeeDeductionAnnualMaximum);
            return this;
        }

        /**
         * The maximum employee deduction amount per year. A null value signifies no limit.
         */
        public Builder employeeDeductionAnnualMaximum(JsonNullable<String> employeeDeductionAnnualMaximum) {
            Utils.checkNotNull(employeeDeductionAnnualMaximum, "employeeDeductionAnnualMaximum");
            this.employeeDeductionAnnualMaximum = employeeDeductionAnnualMaximum;
            return this;
        }


        /**
         * An object representing the type and value of the company contribution.
         */
        public Builder contribution(EmployeeBenefitForCompanyBenefitContribution contribution) {
            Utils.checkNotNull(contribution, "contribution");
            this.contribution = Optional.ofNullable(contribution);
            return this;
        }

        /**
         * An object representing the type and value of the company contribution.
         */
        public Builder contribution(Optional<? extends EmployeeBenefitForCompanyBenefitContribution> contribution) {
            Utils.checkNotNull(contribution, "contribution");
            this.contribution = contribution;
            return this;
        }


        /**
         * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
         * is always true.
         */
        public Builder elective(boolean elective) {
            Utils.checkNotNull(elective, "elective");
            this.elective = Optional.ofNullable(elective);
            return this;
        }

        /**
         * Whether the company contribution is elective (aka matching). For "tiered" contribution types, this
         * is always true.
         */
        public Builder elective(Optional<Boolean> elective) {
            Utils.checkNotNull(elective, "elective");
            this.elective = elective;
            return this;
        }


        /**
         * The maximum company contribution amount per year. A null value signifies no limit.
         */
        public Builder companyContributionAnnualMaximum(String companyContributionAnnualMaximum) {
            Utils.checkNotNull(companyContributionAnnualMaximum, "companyContributionAnnualMaximum");
            this.companyContributionAnnualMaximum = JsonNullable.of(companyContributionAnnualMaximum);
            return this;
        }

        /**
         * The maximum company contribution amount per year. A null value signifies no limit.
         */
        public Builder companyContributionAnnualMaximum(JsonNullable<String> companyContributionAnnualMaximum) {
            Utils.checkNotNull(companyContributionAnnualMaximum, "companyContributionAnnualMaximum");
            this.companyContributionAnnualMaximum = companyContributionAnnualMaximum;
            return this;
        }


        /**
         * Some benefits require additional information to determine their limit.
         * 
         * <p>`Family` and `Individual` are applicable to HSA benefit.
         * 
         * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
         * benefit.
         */
        public Builder limitOption(String limitOption) {
            Utils.checkNotNull(limitOption, "limitOption");
            this.limitOption = JsonNullable.of(limitOption);
            return this;
        }

        /**
         * Some benefits require additional information to determine their limit.
         * 
         * <p>`Family` and `Individual` are applicable to HSA benefit.
         * 
         * <p>`Joint Filing or Single` and `Married and Filing Separately` are applicable to Dependent Care FSA
         * benefit.
         */
        public Builder limitOption(JsonNullable<String> limitOption) {
            Utils.checkNotNull(limitOption, "limitOption");
            this.limitOption = limitOption;
            return this;
        }


        /**
         * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
         * this value for employees over 50.
         */
        public Builder catchUp(boolean catchUp) {
            Utils.checkNotNull(catchUp, "catchUp");
            this.catchUp = JsonNullable.of(catchUp);
            return this;
        }

        /**
         * Whether the employee should use a benefit's "catch up" rate. Only Roth 401k and 401k benefits use
         * this value for employees over 50.
         */
        public Builder catchUp(JsonNullable<Boolean> catchUp) {
            Utils.checkNotNull(catchUp, "catchUp");
            this.catchUp = catchUp;
            return this;
        }


        /**
         * Identifier for a 401(k) loan assigned by the 401(k) provider
         */
        public Builder retirementLoanIdentifier(String retirementLoanIdentifier) {
            Utils.checkNotNull(retirementLoanIdentifier, "retirementLoanIdentifier");
            this.retirementLoanIdentifier = JsonNullable.of(retirementLoanIdentifier);
            return this;
        }

        /**
         * Identifier for a 401(k) loan assigned by the 401(k) provider
         */
        public Builder retirementLoanIdentifier(JsonNullable<String> retirementLoanIdentifier) {
            Utils.checkNotNull(retirementLoanIdentifier, "retirementLoanIdentifier");
            this.retirementLoanIdentifier = retirementLoanIdentifier;
            return this;
        }


        /**
         * The amount that the employee is insured for. Note: company contribution cannot be present if
         * coverage amount is set.
         */
        public Builder coverageAmount(String coverageAmount) {
            Utils.checkNotNull(coverageAmount, "coverageAmount");
            this.coverageAmount = JsonNullable.of(coverageAmount);
            return this;
        }

        /**
         * The amount that the employee is insured for. Note: company contribution cannot be present if
         * coverage amount is set.
         */
        public Builder coverageAmount(JsonNullable<String> coverageAmount) {
            Utils.checkNotNull(coverageAmount, "coverageAmount");
            this.coverageAmount = coverageAmount;
            return this;
        }


        /**
         * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
         * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
         * ignored.
         */
        public Builder deductionReducesTaxableIncome(EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome deductionReducesTaxableIncome) {
            Utils.checkNotNull(deductionReducesTaxableIncome, "deductionReducesTaxableIncome");
            this.deductionReducesTaxableIncome = JsonNullable.of(deductionReducesTaxableIncome);
            return this;
        }

        /**
         * Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life
         * benefits. Note: when the value is not "unset", coverage amount and coverage salary multiplier are
         * ignored.
         */
        public Builder deductionReducesTaxableIncome(JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome> deductionReducesTaxableIncome) {
            Utils.checkNotNull(deductionReducesTaxableIncome, "deductionReducesTaxableIncome");
            this.deductionReducesTaxableIncome = deductionReducesTaxableIncome;
            return this;
        }


        /**
         * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
         * benefits. Note: cannot be set if coverage amount is also set.
         */
        public Builder coverageSalaryMultiplier(String coverageSalaryMultiplier) {
            Utils.checkNotNull(coverageSalaryMultiplier, "coverageSalaryMultiplier");
            this.coverageSalaryMultiplier = JsonNullable.of(coverageSalaryMultiplier);
            return this;
        }

        /**
         * The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life
         * benefits. Note: cannot be set if coverage amount is also set.
         */
        public Builder coverageSalaryMultiplier(JsonNullable<String> coverageSalaryMultiplier) {
            Utils.checkNotNull(coverageSalaryMultiplier, "coverageSalaryMultiplier");
            this.coverageSalaryMultiplier = coverageSalaryMultiplier;
            return this;
        }


        /**
         * The amount to be paid, per pay period, by the company. This field will not appear for tiered
         * contribution types.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder companyContribution(String companyContribution) {
            Utils.checkNotNull(companyContribution, "companyContribution");
            this.companyContribution = Optional.ofNullable(companyContribution);
            return this;
        }

        /**
         * The amount to be paid, per pay period, by the company. This field will not appear for tiered
         * contribution types.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder companyContribution(Optional<String> companyContribution) {
            Utils.checkNotNull(companyContribution, "companyContribution");
            this.companyContribution = companyContribution;
            return this;
        }


        /**
         * Whether the company_contribution value should be treated as a percentage to be added to each
         * payroll. This field will not appear for tiered contribution types.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder contributeAsPercentage(boolean contributeAsPercentage) {
            Utils.checkNotNull(contributeAsPercentage, "contributeAsPercentage");
            this.contributeAsPercentage = Optional.ofNullable(contributeAsPercentage);
            return this;
        }

        /**
         * Whether the company_contribution value should be treated as a percentage to be added to each
         * payroll. This field will not appear for tiered contribution types.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder contributeAsPercentage(Optional<Boolean> contributeAsPercentage) {
            Utils.checkNotNull(contributeAsPercentage, "contributeAsPercentage");
            this.contributeAsPercentage = contributeAsPercentage;
            return this;
        }


        /**
         * The date the employee benefit will start.
         */
        public Builder effectiveDate(LocalDate effectiveDate) {
            Utils.checkNotNull(effectiveDate, "effectiveDate");
            this.effectiveDate = Optional.ofNullable(effectiveDate);
            return this;
        }

        /**
         * The date the employee benefit will start.
         */
        public Builder effectiveDate(Optional<LocalDate> effectiveDate) {
            Utils.checkNotNull(effectiveDate, "effectiveDate");
            this.effectiveDate = effectiveDate;
            return this;
        }


        /**
         * The date the employee benefit will expire. A null value indicates the benefit will not expire.
         */
        public Builder expirationDate(LocalDate expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = JsonNullable.of(expirationDate);
            return this;
        }

        /**
         * The date the employee benefit will expire. A null value indicates the benefit will not expire.
         */
        public Builder expirationDate(JsonNullable<LocalDate> expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = expirationDate;
            return this;
        }


        /**
         * The UUID of the employee to which the benefit belongs.
         */
        public Builder employeeUuid(String employeeUuid) {
            Utils.checkNotNull(employeeUuid, "employeeUuid");
            this.employeeUuid = employeeUuid;
            return this;
        }


        /**
         * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
         */
        public Builder uuid(String uuid) {
            Utils.checkNotNull(uuid, "uuid");
            this.uuid = Optional.ofNullable(uuid);
            return this;
        }

        /**
         * The UUID of the employee benefit. Required for updating an effective dated employee benefit.
         */
        public Builder uuid(Optional<String> uuid) {
            Utils.checkNotNull(uuid, "uuid");
            this.uuid = uuid;
            return this;
        }


        /**
         * The action to perform on the employee benefit. Required for creating/updating an effective dated
         * employee benefit.
         */
        public Builder action(Action action) {
            Utils.checkNotNull(action, "action");
            this.action = Optional.ofNullable(action);
            return this;
        }

        /**
         * The action to perform on the employee benefit. Required for creating/updating an effective dated
         * employee benefit.
         */
        public Builder action(Optional<? extends Action> action) {
            Utils.checkNotNull(action, "action");
            this.action = action;
            return this;
        }

        public Builder additionalProperty(String key, Object value) {
            Utils.checkNotNull(key, "key");
            // we could be strict about null values (force the user
            // to pass `JsonNullable.of(null)`) but likely to be a bit 
            // annoying for additional properties building so we'll 
            // relax preconditions.
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            Utils.checkNotNull(additionalProperties, "additionalProperties");
            this.additionalProperties = additionalProperties;
            return this;
        }

        public EmployeeBenefitForCompanyBenefit build() {
            if (active == null) {
                active = _SINGLETON_VALUE_Active.value();
            }
            if (employeeDeduction == null) {
                employeeDeduction = _SINGLETON_VALUE_EmployeeDeduction.value();
            }
            if (deductAsPercentage == null) {
                deductAsPercentage = _SINGLETON_VALUE_DeductAsPercentage.value();
            }
            if (elective == null) {
                elective = _SINGLETON_VALUE_Elective.value();
            }
            if (catchUp == null) {
                catchUp = _SINGLETON_VALUE_CatchUp.value();
            }
            if (deductionReducesTaxableIncome == null) {
                deductionReducesTaxableIncome = _SINGLETON_VALUE_DeductionReducesTaxableIncome.value();
            }
            if (coverageSalaryMultiplier == null) {
                coverageSalaryMultiplier = _SINGLETON_VALUE_CoverageSalaryMultiplier.value();
            }
            if (companyContribution == null) {
                companyContribution = _SINGLETON_VALUE_CompanyContribution.value();
            }
            if (contributeAsPercentage == null) {
                contributeAsPercentage = _SINGLETON_VALUE_ContributeAsPercentage.value();
            }

            return new EmployeeBenefitForCompanyBenefit(
                version, active, employeeDeduction,
                deductAsPercentage, employeeDeductionAnnualMaximum, contribution,
                elective, companyContributionAnnualMaximum, limitOption,
                catchUp, retirementLoanIdentifier, coverageAmount,
                deductionReducesTaxableIncome, coverageSalaryMultiplier, companyContribution,
                contributeAsPercentage, effectiveDate, expirationDate,
                employeeUuid, uuid, action)
                .withAdditionalProperties(additionalProperties);
        }


        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_Active =
                new LazySingletonValue<>(
                        "active",
                        "true",
                        new TypeReference<Optional<Boolean>>() {});

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_EmployeeDeduction =
                new LazySingletonValue<>(
                        "employee_deduction",
                        "\"0.00\"",
                        new TypeReference<Optional<String>>() {});

        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_DeductAsPercentage =
                new LazySingletonValue<>(
                        "deduct_as_percentage",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});

        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_Elective =
                new LazySingletonValue<>(
                        "elective",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});

        private static final LazySingletonValue<JsonNullable<Boolean>> _SINGLETON_VALUE_CatchUp =
                new LazySingletonValue<>(
                        "catch_up",
                        "false",
                        new TypeReference<JsonNullable<Boolean>>() {});

        private static final LazySingletonValue<JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome>> _SINGLETON_VALUE_DeductionReducesTaxableIncome =
                new LazySingletonValue<>(
                        "deduction_reduces_taxable_income",
                        "\"unset\"",
                        new TypeReference<JsonNullable<? extends EmployeeBenefitForCompanyBenefitDeductionReducesTaxableIncome>>() {});

        private static final LazySingletonValue<JsonNullable<String>> _SINGLETON_VALUE_CoverageSalaryMultiplier =
                new LazySingletonValue<>(
                        "coverage_salary_multiplier",
                        "\"0.00\"",
                        new TypeReference<JsonNullable<String>>() {});

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_CompanyContribution =
                new LazySingletonValue<>(
                        "company_contribution",
                        "\"0.00\"",
                        new TypeReference<Optional<String>>() {});

        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_ContributeAsPercentage =
                new LazySingletonValue<>(
                        "contribute_as_percentage",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});
    }
}
