/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum IdentityVerificationStatus {
    PASS("Pass"),
    FAIL("Fail"),
    SKIPPED("Skipped");

    @JsonValue
    private final String value;

    IdentityVerificationStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<IdentityVerificationStatus> fromValue(String value) {
        for (IdentityVerificationStatus o: IdentityVerificationStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

