/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PayrollCreditBlockerTypeStatus
 * 
 * <p>The status of the credit blocker
 */
public enum PayrollCreditBlockerTypeStatus {
    UNRESOLVED("unresolved"),
    PENDING_REVIEW("pending_review"),
    RESOLVED("resolved"),
    FAILED("failed");

    @JsonValue
    private final String value;

    PayrollCreditBlockerTypeStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PayrollCreditBlockerTypeStatus> fromValue(String value) {
        for (PayrollCreditBlockerTypeStatus o: PayrollCreditBlockerTypeStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

