/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PayrollType
 * 
 * <p>Whether it is regular pay period or transition pay period.
 */
public enum PayrollType {
    REGULAR("regular"),
    TRANSITION("transition");

    @JsonValue
    private final String value;

    PayrollType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PayrollType> fromValue(String value) {
        for (PayrollType o: PayrollType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

