/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gusto.embedded_api_v_2025_11_15.utils.LazySingletonValue;
import com.gusto.embedded_api_v_2025_11_15.utils.Utils;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class RefreshTokenAuthentication {
    /**
     * A new access token that can be used for subsequent authenticated requests
     */
    @JsonProperty("access_token")
    private String accessToken;

    /**
     * The literal string 'Bearer'
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token_type")
    private Optional<String> tokenType;

    /**
     * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
     * continue making authenticated requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires_in")
    private Optional<Double> expiresIn;

    /**
     * Datetime for when the new access token is created.
     */
    @JsonProperty("created_at")
    private double createdAt;

    /**
     * A token that must be passed to the refresh token endpoint to get a new authenticated token.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refresh_token")
    private Optional<String> refreshToken;

    /**
     * All of the scopes for which the access token provides access.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scope")
    private Optional<String> scope;

    @JsonCreator
    public RefreshTokenAuthentication(
            @JsonProperty("access_token") String accessToken,
            @JsonProperty("token_type") Optional<String> tokenType,
            @JsonProperty("expires_in") Optional<Double> expiresIn,
            @JsonProperty("created_at") double createdAt,
            @JsonProperty("refresh_token") Optional<String> refreshToken,
            @JsonProperty("scope") Optional<String> scope) {
        Utils.checkNotNull(accessToken, "accessToken");
        Utils.checkNotNull(tokenType, "tokenType");
        Utils.checkNotNull(expiresIn, "expiresIn");
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(refreshToken, "refreshToken");
        Utils.checkNotNull(scope, "scope");
        this.accessToken = accessToken;
        this.tokenType = tokenType;
        this.expiresIn = expiresIn;
        this.createdAt = createdAt;
        this.refreshToken = refreshToken;
        this.scope = scope;
    }
    
    public RefreshTokenAuthentication(
            String accessToken,
            double createdAt) {
        this(accessToken, Optional.empty(), Optional.empty(),
            createdAt, Optional.empty(), Optional.empty());
    }

    /**
     * A new access token that can be used for subsequent authenticated requests
     */
    @JsonIgnore
    public String accessToken() {
        return accessToken;
    }

    /**
     * The literal string 'Bearer'
     */
    @JsonIgnore
    public Optional<String> tokenType() {
        return tokenType;
    }

    /**
     * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
     * continue making authenticated requests.
     */
    @JsonIgnore
    public Optional<Double> expiresIn() {
        return expiresIn;
    }

    /**
     * Datetime for when the new access token is created.
     */
    @JsonIgnore
    public double createdAt() {
        return createdAt;
    }

    /**
     * A token that must be passed to the refresh token endpoint to get a new authenticated token.
     */
    @JsonIgnore
    public Optional<String> refreshToken() {
        return refreshToken;
    }

    /**
     * All of the scopes for which the access token provides access.
     */
    @JsonIgnore
    public Optional<String> scope() {
        return scope;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A new access token that can be used for subsequent authenticated requests
     */
    public RefreshTokenAuthentication withAccessToken(String accessToken) {
        Utils.checkNotNull(accessToken, "accessToken");
        this.accessToken = accessToken;
        return this;
    }

    /**
     * The literal string 'Bearer'
     */
    public RefreshTokenAuthentication withTokenType(String tokenType) {
        Utils.checkNotNull(tokenType, "tokenType");
        this.tokenType = Optional.ofNullable(tokenType);
        return this;
    }


    /**
     * The literal string 'Bearer'
     */
    public RefreshTokenAuthentication withTokenType(Optional<String> tokenType) {
        Utils.checkNotNull(tokenType, "tokenType");
        this.tokenType = tokenType;
        return this;
    }

    /**
     * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
     * continue making authenticated requests.
     */
    public RefreshTokenAuthentication withExpiresIn(double expiresIn) {
        Utils.checkNotNull(expiresIn, "expiresIn");
        this.expiresIn = Optional.ofNullable(expiresIn);
        return this;
    }


    /**
     * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
     * continue making authenticated requests.
     */
    public RefreshTokenAuthentication withExpiresIn(Optional<Double> expiresIn) {
        Utils.checkNotNull(expiresIn, "expiresIn");
        this.expiresIn = expiresIn;
        return this;
    }

    /**
     * Datetime for when the new access token is created.
     */
    public RefreshTokenAuthentication withCreatedAt(double createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    /**
     * A token that must be passed to the refresh token endpoint to get a new authenticated token.
     */
    public RefreshTokenAuthentication withRefreshToken(String refreshToken) {
        Utils.checkNotNull(refreshToken, "refreshToken");
        this.refreshToken = Optional.ofNullable(refreshToken);
        return this;
    }


    /**
     * A token that must be passed to the refresh token endpoint to get a new authenticated token.
     */
    public RefreshTokenAuthentication withRefreshToken(Optional<String> refreshToken) {
        Utils.checkNotNull(refreshToken, "refreshToken");
        this.refreshToken = refreshToken;
        return this;
    }

    /**
     * All of the scopes for which the access token provides access.
     */
    public RefreshTokenAuthentication withScope(String scope) {
        Utils.checkNotNull(scope, "scope");
        this.scope = Optional.ofNullable(scope);
        return this;
    }


    /**
     * All of the scopes for which the access token provides access.
     */
    public RefreshTokenAuthentication withScope(Optional<String> scope) {
        Utils.checkNotNull(scope, "scope");
        this.scope = scope;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RefreshTokenAuthentication other = (RefreshTokenAuthentication) o;
        return 
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.refreshToken, other.refreshToken) &&
            Utils.enhancedDeepEquals(this.scope, other.scope);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessToken, tokenType, expiresIn,
            createdAt, refreshToken, scope);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RefreshTokenAuthentication.class,
                "accessToken", accessToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn,
                "createdAt", createdAt,
                "refreshToken", refreshToken,
                "scope", scope);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accessToken;

        private Optional<String> tokenType;

        private Optional<Double> expiresIn;

        private Double createdAt;

        private Optional<String> refreshToken = Optional.empty();

        private Optional<String> scope = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A new access token that can be used for subsequent authenticated requests
         */
        public Builder accessToken(String accessToken) {
            Utils.checkNotNull(accessToken, "accessToken");
            this.accessToken = accessToken;
            return this;
        }


        /**
         * The literal string 'Bearer'
         */
        public Builder tokenType(String tokenType) {
            Utils.checkNotNull(tokenType, "tokenType");
            this.tokenType = Optional.ofNullable(tokenType);
            return this;
        }

        /**
         * The literal string 'Bearer'
         */
        public Builder tokenType(Optional<String> tokenType) {
            Utils.checkNotNull(tokenType, "tokenType");
            this.tokenType = tokenType;
            return this;
        }


        /**
         * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
         * continue making authenticated requests.
         */
        public Builder expiresIn(double expiresIn) {
            Utils.checkNotNull(expiresIn, "expiresIn");
            this.expiresIn = Optional.ofNullable(expiresIn);
            return this;
        }

        /**
         * The TTL of this token. After this amount of time, you must hit the refresh token endpoint to
         * continue making authenticated requests.
         */
        public Builder expiresIn(Optional<Double> expiresIn) {
            Utils.checkNotNull(expiresIn, "expiresIn");
            this.expiresIn = expiresIn;
            return this;
        }


        /**
         * Datetime for when the new access token is created.
         */
        public Builder createdAt(double createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }


        /**
         * A token that must be passed to the refresh token endpoint to get a new authenticated token.
         */
        public Builder refreshToken(String refreshToken) {
            Utils.checkNotNull(refreshToken, "refreshToken");
            this.refreshToken = Optional.ofNullable(refreshToken);
            return this;
        }

        /**
         * A token that must be passed to the refresh token endpoint to get a new authenticated token.
         */
        public Builder refreshToken(Optional<String> refreshToken) {
            Utils.checkNotNull(refreshToken, "refreshToken");
            this.refreshToken = refreshToken;
            return this;
        }


        /**
         * All of the scopes for which the access token provides access.
         */
        public Builder scope(String scope) {
            Utils.checkNotNull(scope, "scope");
            this.scope = Optional.ofNullable(scope);
            return this;
        }

        /**
         * All of the scopes for which the access token provides access.
         */
        public Builder scope(Optional<String> scope) {
            Utils.checkNotNull(scope, "scope");
            this.scope = scope;
            return this;
        }

        public RefreshTokenAuthentication build() {
            if (tokenType == null) {
                tokenType = _SINGLETON_VALUE_TokenType.value();
            }
            if (expiresIn == null) {
                expiresIn = _SINGLETON_VALUE_ExpiresIn.value();
            }

            return new RefreshTokenAuthentication(
                accessToken, tokenType, expiresIn,
                createdAt, refreshToken, scope);
        }


        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_TokenType =
                new LazySingletonValue<>(
                        "token_type",
                        "\"Bearer\"",
                        new TypeReference<Optional<String>>() {});

        private static final LazySingletonValue<Optional<Double>> _SINGLETON_VALUE_ExpiresIn =
                new LazySingletonValue<>(
                        "expires_in",
                        "7200",
                        new TypeReference<Optional<Double>>() {});
    }
}
