/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api_v_2025_11_15;

import static com.gusto.embedded_api_v_2025_11_15.operations.Operations.AsyncRequestOperation;

import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1HistoricalEmployeesHeaderXGustoAPIVersion;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1HistoricalEmployeesRequest;
import com.gusto.embedded_api_v_2025_11_15.models.operations.PutV1HistoricalEmployeesRequestBody;
import com.gusto.embedded_api_v_2025_11_15.models.operations.async.PutV1HistoricalEmployeesRequestBuilder;
import com.gusto.embedded_api_v_2025_11_15.models.operations.async.PutV1HistoricalEmployeesResponse;
import com.gusto.embedded_api_v_2025_11_15.operations.PutV1HistoricalEmployees;
import com.gusto.embedded_api_v_2025_11_15.utils.Headers;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;


public class AsyncHistoricalEmployees {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final HistoricalEmployees syncSDK;

    AsyncHistoricalEmployees(HistoricalEmployees syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public HistoricalEmployees sync() {
        return syncSDK;
    }


    /**
     * Update a historical employee
     * 
     * <p>Update a historical employee, an employee that was previously dismissed from the company in the
     * current year.
     * 
     * <p>scope: `employees:manage employees:write`
     * 
     * <p>If set, this operation will use Security#companyAccessAuth from the global security.
     * 
     * @return The async call builder
     */
    public PutV1HistoricalEmployeesRequestBuilder update() {
        return new PutV1HistoricalEmployeesRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a historical employee
     * 
     * <p>Update a historical employee, an employee that was previously dismissed from the company in the
     * current year.
     * 
     * <p>scope: `employees:manage employees:write`
     * 
     * <p>If set, this operation will use Security#companyAccessAuth from the global security.
     * 
     * @param companyUuid The UUID of the company that will employ this historical record.
     * @param historicalEmployeeUuid The UUID of the historical employee returned from create or list responses.
     * @param requestBody Request body for creating or updating a **historical employee**—someone who already separated from the company and must appear on year-to-date or tax filings without receiving ongoing payroll.
     *         
     *         Send this object under the JSON root key `employee`. All dates are ISO 8601 (`YYYY-MM-DD`). Use a `work_address.location_uuid` returned from your company locations API for an active work site.
     *         
     * @return {@code CompletableFuture<PutV1HistoricalEmployeesResponse>} - The async response
     */
    public CompletableFuture<PutV1HistoricalEmployeesResponse> update(
            String companyUuid, String historicalEmployeeUuid,
            PutV1HistoricalEmployeesRequestBody requestBody) {
        return update(
                Optional.empty(), companyUuid, historicalEmployeeUuid,
                requestBody);
    }

    /**
     * Update a historical employee
     * 
     * <p>Update a historical employee, an employee that was previously dismissed from the company in the
     * current year.
     * 
     * <p>scope: `employees:manage employees:write`
     * 
     * <p>If set, this operation will use Security#companyAccessAuth from the global security.
     * 
     * @param xGustoAPIVersion Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
     * @param companyUuid The UUID of the company that will employ this historical record.
     * @param historicalEmployeeUuid The UUID of the historical employee returned from create or list responses.
     * @param requestBody Request body for creating or updating a **historical employee**—someone who already separated from the company and must appear on year-to-date or tax filings without receiving ongoing payroll.
     *         
     *         Send this object under the JSON root key `employee`. All dates are ISO 8601 (`YYYY-MM-DD`). Use a `work_address.location_uuid` returned from your company locations API for an active work site.
     *         
     * @return {@code CompletableFuture<PutV1HistoricalEmployeesResponse>} - The async response
     */
    public CompletableFuture<PutV1HistoricalEmployeesResponse> update(
            Optional<? extends PutV1HistoricalEmployeesHeaderXGustoAPIVersion> xGustoAPIVersion, String companyUuid,
            String historicalEmployeeUuid, PutV1HistoricalEmployeesRequestBody requestBody) {
        PutV1HistoricalEmployeesRequest request =
            PutV1HistoricalEmployeesRequest
                .builder()
                .xGustoAPIVersion(xGustoAPIVersion)
                .companyUuid(companyUuid)
                .historicalEmployeeUuid(historicalEmployeeUuid)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<PutV1HistoricalEmployeesRequest, PutV1HistoricalEmployeesResponse> operation
              = new PutV1HistoricalEmployees.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
