/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class ContractorPaymentMethod {
    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    private Optional<String> version;

    /**
     * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
     * If type is Direct Deposit, `split_by` and `splits` are required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private JsonNullable<? extends ContractorPaymentMethodType> type;

    /**
     * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
     * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
     * must be `null` to capture the remainder.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("split_by")
    private JsonNullable<? extends ContractorPaymentMethodSplitBy> splitBy;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("splits")
    private JsonNullable<? extends List<PaymentMethodBankAccount>> splits;

    @JsonCreator
    public ContractorPaymentMethod(
            @JsonProperty("version") Optional<String> version,
            @JsonProperty("type") JsonNullable<? extends ContractorPaymentMethodType> type,
            @JsonProperty("split_by") JsonNullable<? extends ContractorPaymentMethodSplitBy> splitBy,
            @JsonProperty("splits") JsonNullable<? extends List<PaymentMethodBankAccount>> splits) {
        Utils.checkNotNull(version, "version");
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(splitBy, "splitBy");
        Utils.checkNotNull(splits, "splits");
        this.version = version;
        this.type = type;
        this.splitBy = splitBy;
        this.splits = splits;
    }
    
    public ContractorPaymentMethod() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined());
    }

    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    @JsonIgnore
    public Optional<String> version() {
        return version;
    }

    /**
     * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
     * If type is Direct Deposit, `split_by` and `splits` are required.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ContractorPaymentMethodType> type() {
        return (JsonNullable<ContractorPaymentMethodType>) type;
    }

    /**
     * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
     * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
     * must be `null` to capture the remainder.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<ContractorPaymentMethodSplitBy> splitBy() {
        return (JsonNullable<ContractorPaymentMethodSplitBy>) splitBy;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<List<PaymentMethodBankAccount>> splits() {
        return (JsonNullable<List<PaymentMethodBankAccount>>) splits;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    public ContractorPaymentMethod withVersion(String version) {
        Utils.checkNotNull(version, "version");
        this.version = Optional.ofNullable(version);
        return this;
    }


    /**
     * The current version of the object. See the [versioning
     * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
     * field.
     */
    public ContractorPaymentMethod withVersion(Optional<String> version) {
        Utils.checkNotNull(version, "version");
        this.version = version;
        return this;
    }

    /**
     * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
     * If type is Direct Deposit, `split_by` and `splits` are required.
     */
    public ContractorPaymentMethod withType(ContractorPaymentMethodType type) {
        Utils.checkNotNull(type, "type");
        this.type = JsonNullable.of(type);
        return this;
    }

    /**
     * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
     * If type is Direct Deposit, `split_by` and `splits` are required.
     */
    public ContractorPaymentMethod withType(JsonNullable<? extends ContractorPaymentMethodType> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
     * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
     * must be `null` to capture the remainder.
     */
    public ContractorPaymentMethod withSplitBy(ContractorPaymentMethodSplitBy splitBy) {
        Utils.checkNotNull(splitBy, "splitBy");
        this.splitBy = JsonNullable.of(splitBy);
        return this;
    }

    /**
     * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
     * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
     * must be `null` to capture the remainder.
     */
    public ContractorPaymentMethod withSplitBy(JsonNullable<? extends ContractorPaymentMethodSplitBy> splitBy) {
        Utils.checkNotNull(splitBy, "splitBy");
        this.splitBy = splitBy;
        return this;
    }

    public ContractorPaymentMethod withSplits(List<PaymentMethodBankAccount> splits) {
        Utils.checkNotNull(splits, "splits");
        this.splits = JsonNullable.of(splits);
        return this;
    }

    public ContractorPaymentMethod withSplits(JsonNullable<? extends List<PaymentMethodBankAccount>> splits) {
        Utils.checkNotNull(splits, "splits");
        this.splits = splits;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContractorPaymentMethod other = (ContractorPaymentMethod) o;
        return 
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.splitBy, other.splitBy) &&
            Utils.enhancedDeepEquals(this.splits, other.splits);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            version, type, splitBy,
            splits);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ContractorPaymentMethod.class,
                "version", version,
                "type", type,
                "splitBy", splitBy,
                "splits", splits);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> version = Optional.empty();

        private JsonNullable<? extends ContractorPaymentMethodType> type = JsonNullable.undefined();

        private JsonNullable<? extends ContractorPaymentMethodSplitBy> splitBy = JsonNullable.undefined();

        private JsonNullable<? extends List<PaymentMethodBankAccount>> splits = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The current version of the object. See the [versioning
         * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
         * field.
         */
        public Builder version(String version) {
            Utils.checkNotNull(version, "version");
            this.version = Optional.ofNullable(version);
            return this;
        }

        /**
         * The current version of the object. See the [versioning
         * guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this
         * field.
         */
        public Builder version(Optional<String> version) {
            Utils.checkNotNull(version, "version");
            this.version = version;
            return this;
        }


        /**
         * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
         * If type is Direct Deposit, `split_by` and `splits` are required.
         */
        public Builder type(ContractorPaymentMethodType type) {
            Utils.checkNotNull(type, "type");
            this.type = JsonNullable.of(type);
            return this;
        }

        /**
         * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated.
         * If type is Direct Deposit, `split_by` and `splits` are required.
         */
        public Builder type(JsonNullable<? extends ContractorPaymentMethodType> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        /**
         * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
         * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
         * must be `null` to capture the remainder.
         */
        public Builder splitBy(ContractorPaymentMethodSplitBy splitBy) {
            Utils.checkNotNull(splitBy, "splitBy");
            this.splitBy = JsonNullable.of(splitBy);
            return this;
        }

        /**
         * Describes how the payment will be split. If `split_by` is Percentage, then the `split` amounts must
         * add up to exactly 100. If `split_by` is Amount, then values are in cents and the last split amount
         * must be `null` to capture the remainder.
         */
        public Builder splitBy(JsonNullable<? extends ContractorPaymentMethodSplitBy> splitBy) {
            Utils.checkNotNull(splitBy, "splitBy");
            this.splitBy = splitBy;
            return this;
        }


        public Builder splits(List<PaymentMethodBankAccount> splits) {
            Utils.checkNotNull(splits, "splits");
            this.splits = JsonNullable.of(splits);
            return this;
        }

        public Builder splits(JsonNullable<? extends List<PaymentMethodBankAccount>> splits) {
            Utils.checkNotNull(splits, "splits");
            this.splits = splits;
            return this;
        }

        public ContractorPaymentMethod build() {

            return new ContractorPaymentMethod(
                version, type, splitBy,
                splits);
        }

    }
}
