/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gusto.embedded_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gusto.embedded_api.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * PayScheduleCreateRequest
 * 
 * <p>Request body for creating a pay schedule. Required when a company has no pay schedules (onboarding)
 * or when adding an additional schedule. Be sure to [check state
 * laws](https://www.dol.gov/agencies/whd/state/payday) to know what schedule is right for your
 * customers.
 * 
 * <p>- **anchor_pay_date**: The first date that employees on this pay schedule will be paid (first
 * company payday).
 * - **anchor_end_of_pay_period**: The last date of the first pay period; can be the same as
 * anchor_pay_date.
 */
public class PayScheduleCreateRequest {

    @JsonProperty("frequency")
    private Frequency frequency;


    @JsonProperty("anchor_pay_date")
    private LocalDate anchorPayDate;


    @JsonProperty("anchor_end_of_pay_period")
    private LocalDate anchorEndOfPayPeriod;

    /**
     * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
     * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
     * will be null for pay schedules with other frequencies.
     * 
     * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
     * week.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("day_1")
    private JsonNullable<Long> day1;

    /**
     * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
     * field is the second pay date for pay schedules with the "Twice per month" frequency. For
     * semi-monthly pay schedules, set this field to 31.
     * 
     * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
     * null for pay schedules with other frequencies.
     * 
     * <p>On create: only for Twice per month; omit or null for other frequencies.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("day_2")
    private JsonNullable<Long> day2;

    /**
     * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
     * 
     * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
     * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
     * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
     * was set.
     * 
     * <p>When provided, the value you set is stored and returned.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_name")
    private JsonNullable<String> customName;

    @JsonCreator
    public PayScheduleCreateRequest(
            @JsonProperty("frequency") Frequency frequency,
            @JsonProperty("anchor_pay_date") LocalDate anchorPayDate,
            @JsonProperty("anchor_end_of_pay_period") LocalDate anchorEndOfPayPeriod,
            @JsonProperty("day_1") JsonNullable<Long> day1,
            @JsonProperty("day_2") JsonNullable<Long> day2,
            @JsonProperty("custom_name") JsonNullable<String> customName) {
        Utils.checkNotNull(frequency, "frequency");
        Utils.checkNotNull(anchorPayDate, "anchorPayDate");
        Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
        Utils.checkNotNull(day1, "day1");
        Utils.checkNotNull(day2, "day2");
        Utils.checkNotNull(customName, "customName");
        this.frequency = frequency;
        this.anchorPayDate = anchorPayDate;
        this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
        this.day1 = day1;
        this.day2 = day2;
        this.customName = customName;
    }
    
    public PayScheduleCreateRequest(
            Frequency frequency,
            LocalDate anchorPayDate,
            LocalDate anchorEndOfPayPeriod) {
        this(frequency, anchorPayDate, anchorEndOfPayPeriod,
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public Frequency frequency() {
        return frequency;
    }

    @JsonIgnore
    public LocalDate anchorPayDate() {
        return anchorPayDate;
    }

    @JsonIgnore
    public LocalDate anchorEndOfPayPeriod() {
        return anchorEndOfPayPeriod;
    }

    /**
     * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
     * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
     * will be null for pay schedules with other frequencies.
     * 
     * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
     * week.
     */
    @JsonIgnore
    public JsonNullable<Long> day1() {
        return day1;
    }

    /**
     * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
     * field is the second pay date for pay schedules with the "Twice per month" frequency. For
     * semi-monthly pay schedules, set this field to 31.
     * 
     * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
     * null for pay schedules with other frequencies.
     * 
     * <p>On create: only for Twice per month; omit or null for other frequencies.
     */
    @JsonIgnore
    public JsonNullable<Long> day2() {
        return day2;
    }

    /**
     * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
     * 
     * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
     * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
     * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
     * was set.
     * 
     * <p>When provided, the value you set is stored and returned.
     */
    @JsonIgnore
    public JsonNullable<String> customName() {
        return customName;
    }

    public static Builder builder() {
        return new Builder();
    }


    public PayScheduleCreateRequest withFrequency(Frequency frequency) {
        Utils.checkNotNull(frequency, "frequency");
        this.frequency = frequency;
        return this;
    }

    public PayScheduleCreateRequest withAnchorPayDate(LocalDate anchorPayDate) {
        Utils.checkNotNull(anchorPayDate, "anchorPayDate");
        this.anchorPayDate = anchorPayDate;
        return this;
    }

    public PayScheduleCreateRequest withAnchorEndOfPayPeriod(LocalDate anchorEndOfPayPeriod) {
        Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
        this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
        return this;
    }

    /**
     * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
     * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
     * will be null for pay schedules with other frequencies.
     * 
     * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
     * week.
     */
    public PayScheduleCreateRequest withDay1(long day1) {
        Utils.checkNotNull(day1, "day1");
        this.day1 = JsonNullable.of(day1);
        return this;
    }

    /**
     * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
     * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
     * will be null for pay schedules with other frequencies.
     * 
     * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
     * week.
     */
    public PayScheduleCreateRequest withDay1(JsonNullable<Long> day1) {
        Utils.checkNotNull(day1, "day1");
        this.day1 = day1;
        return this;
    }

    /**
     * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
     * field is the second pay date for pay schedules with the "Twice per month" frequency. For
     * semi-monthly pay schedules, set this field to 31.
     * 
     * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
     * null for pay schedules with other frequencies.
     * 
     * <p>On create: only for Twice per month; omit or null for other frequencies.
     */
    public PayScheduleCreateRequest withDay2(long day2) {
        Utils.checkNotNull(day2, "day2");
        this.day2 = JsonNullable.of(day2);
        return this;
    }

    /**
     * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
     * field is the second pay date for pay schedules with the "Twice per month" frequency. For
     * semi-monthly pay schedules, set this field to 31.
     * 
     * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
     * null for pay schedules with other frequencies.
     * 
     * <p>On create: only for Twice per month; omit or null for other frequencies.
     */
    public PayScheduleCreateRequest withDay2(JsonNullable<Long> day2) {
        Utils.checkNotNull(day2, "day2");
        this.day2 = day2;
        return this;
    }

    /**
     * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
     * 
     * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
     * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
     * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
     * was set.
     * 
     * <p>When provided, the value you set is stored and returned.
     */
    public PayScheduleCreateRequest withCustomName(String customName) {
        Utils.checkNotNull(customName, "customName");
        this.customName = JsonNullable.of(customName);
        return this;
    }

    /**
     * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
     * 
     * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
     * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
     * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
     * was set.
     * 
     * <p>When provided, the value you set is stored and returned.
     */
    public PayScheduleCreateRequest withCustomName(JsonNullable<String> customName) {
        Utils.checkNotNull(customName, "customName");
        this.customName = customName;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayScheduleCreateRequest other = (PayScheduleCreateRequest) o;
        return 
            Utils.enhancedDeepEquals(this.frequency, other.frequency) &&
            Utils.enhancedDeepEquals(this.anchorPayDate, other.anchorPayDate) &&
            Utils.enhancedDeepEquals(this.anchorEndOfPayPeriod, other.anchorEndOfPayPeriod) &&
            Utils.enhancedDeepEquals(this.day1, other.day1) &&
            Utils.enhancedDeepEquals(this.day2, other.day2) &&
            Utils.enhancedDeepEquals(this.customName, other.customName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            frequency, anchorPayDate, anchorEndOfPayPeriod,
            day1, day2, customName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PayScheduleCreateRequest.class,
                "frequency", frequency,
                "anchorPayDate", anchorPayDate,
                "anchorEndOfPayPeriod", anchorEndOfPayPeriod,
                "day1", day1,
                "day2", day2,
                "customName", customName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Frequency frequency;

        private LocalDate anchorPayDate;

        private LocalDate anchorEndOfPayPeriod;

        private JsonNullable<Long> day1 = JsonNullable.undefined();

        private JsonNullable<Long> day2 = JsonNullable.undefined();

        private JsonNullable<String> customName = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder frequency(Frequency frequency) {
            Utils.checkNotNull(frequency, "frequency");
            this.frequency = frequency;
            return this;
        }


        public Builder anchorPayDate(LocalDate anchorPayDate) {
            Utils.checkNotNull(anchorPayDate, "anchorPayDate");
            this.anchorPayDate = anchorPayDate;
            return this;
        }


        public Builder anchorEndOfPayPeriod(LocalDate anchorEndOfPayPeriod) {
            Utils.checkNotNull(anchorEndOfPayPeriod, "anchorEndOfPayPeriod");
            this.anchorEndOfPayPeriod = anchorEndOfPayPeriod;
            return this;
        }


        /**
         * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
         * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
         * will be null for pay schedules with other frequencies.
         * 
         * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
         * week.
         */
        public Builder day1(long day1) {
            Utils.checkNotNull(day1, "day1");
            this.day1 = JsonNullable.of(day1);
            return this;
        }

        /**
         * An integer between 1 and 31 indicating the first day of the month that employees are paid. This
         * field is only relevant for pay schedules with the "Twice per month" and "Monthly" frequencies. It
         * will be null for pay schedules with other frequencies.
         * 
         * <p>On create: required for Twice per month and Monthly; omit or null for Every week and Every other
         * week.
         */
        public Builder day1(JsonNullable<Long> day1) {
            Utils.checkNotNull(day1, "day1");
            this.day1 = day1;
            return this;
        }


        /**
         * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
         * field is the second pay date for pay schedules with the "Twice per month" frequency. For
         * semi-monthly pay schedules, set this field to 31.
         * 
         * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
         * null for pay schedules with other frequencies.
         * 
         * <p>On create: only for Twice per month; omit or null for other frequencies.
         */
        public Builder day2(long day2) {
            Utils.checkNotNull(day2, "day2");
            this.day2 = JsonNullable.of(day2);
            return this;
        }

        /**
         * An integer between 1 and 31 indicating the second day of the month that employees are paid. This
         * field is the second pay date for pay schedules with the "Twice per month" frequency. For
         * semi-monthly pay schedules, set this field to 31.
         * 
         * <p>For months shorter than 31 days, the second pay date is set to the last day of the month. It will be
         * null for pay schedules with other frequencies.
         * 
         * <p>On create: only for Twice per month; omit or null for other frequencies.
         */
        public Builder day2(JsonNullable<Long> day2) {
            Utils.checkNotNull(day2, "day2");
            this.day2 = day2;
            return this;
        }


        /**
         * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
         * 
         * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
         * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
         * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
         * was set.
         * 
         * <p>When provided, the value you set is stored and returned.
         */
        public Builder customName(String customName) {
            Utils.checkNotNull(customName, "customName");
            this.customName = JsonNullable.of(customName);
            return this;
        }

        /**
         * A custom pay schedule name; defaults to the pay frequency description when null or omitted.
         * 
         * <p>When null or omitted, the system generates a description from the pay frequency and pay days (e.g.
         * "every 1st and 15th of the month" for twice-monthly, "every 11th of the month" for monthly, "every
         * Friday" for weekly). The response returns this generated value in `custom_name` when no custom name
         * was set.
         * 
         * <p>When provided, the value you set is stored and returned.
         */
        public Builder customName(JsonNullable<String> customName) {
            Utils.checkNotNull(customName, "customName");
            this.customName = customName;
            return this;
        }

        public PayScheduleCreateRequest build() {

            return new PayScheduleCreateRequest(
                frequency, anchorPayDate, anchorEndOfPayPeriod,
                day1, day2, customName);
        }

    }
}
